import { useEffect, useState } from 'react'
import { api, errorMessage } from '../api'
import './workbench.css'
import FormDraftToolbar from '../control-center/FormDraftToolbar'
import PathView from './PathView'
import ThroughputView from './ThroughputView'
type Server = { id: number; name: string }
type Target = { id: string; name: string; host: string; region: string; carrier: string; purpose: string; authorization: string; authorized_until: number | null }
type Tool = { id: string; version: string; license: string; source_url: string; licensed: boolean; platforms: string[] }
type Provider = { id: string; name: string; endpoint: string; credential_ref: string | null; daily_quota: number; cache_seconds: number; disabled: boolean }
type CheckValue = string | number | boolean | string[] | number[] | null
type Check = { kind: string } & Record<string, CheckValue>
type Source = { kind: 'panel' } | { kind: 'server'; server_id: number } | { kind: 'group'; server_ids: number[] }
type Step = { name: string; source: Source; check: Check; stop_on_failure: boolean }
type Budget = { duration_secs: number; memory_bytes: number; disk_bytes: number; traffic_bytes: number; rate_bps: number; concurrency: number; cpu_percent: number; cpu_weight: number; pause_on_service_error: boolean }
type Plan = { name: string; budget: Budget; steps: Step[]; schedule: { interval_secs: number; first_run_at: number; timezone: string; missed_window: string } | null }
type Run = { id: string; name: string; status: string; current_step: number; error: string | null; created_at: number }
type SavedPlan = { id: string; revision: number; enabled: boolean; definition: { plan: Plan } }
type Result = { id: string; step_index: number; source_server: number | null; role: string; job_id: string | null; status: string; observation: Record<string, unknown> | null; cleanup_confirmed: boolean; cleanup_origin: string; error: string | null; sections: { name: string; text: string; complete: boolean; collected_at: number }[] }
type Report = { summary: { step_count: number; result_count: number; succeeded: number; failed: number; cleanup_pending: number }; id: string; status: string; error: string | null; results: Result[]; snapshot: { plan: Plan }; physical_acceptance: string }
const labels: Record<string, string> = { tcp: 'TCP连接', icmp: 'ICMP往返与丢包', http: 'HTTP / HTTPS', dns: 'DNS多解析器', tls: 'TLS证书', udp: 'UDP有效请求', quic: 'QUIC / HTTP3', web_socket: 'WebSocket连接保持', route: 'Traceroute / NextTrace', mtr: 'MTR有限采样', throughput: '双端iperf3吞吐', cpu: 'CPU单线程 / 多线程', memory: '内存读写', disk: 'fio磁盘顺序 / 随机', stability: '持续稳定性', hardware_info: '物理硬件健康', exit: '出口地址发现', ip_info: '多来源IP资料', mail: '自有邮件服务', geekbench_import: 'Geekbench获准结果导入', speedtest: 'Speedtest报告', node_quality_full: 'NodeQuality完整验机（门禁）' }
const fieldLabels: Record<string, string> = { target_id: '授权目标', port: '目标端口', family: '地址族', samples: '样本数量', packet_bytes: 'ICMP包大小（字节）', url: '请求URL', expected_status: '预期状态码', expected_content: '预期内容', follow_redirects: '跟随同目标重定向', resolvers: '解析器IP（逗号分隔）', record_type: 'DNS记录类型', expected: '预期记录（逗号分隔）', server_name: 'TLS验证域名', request_hex: '有效UDP请求（十六进制）', expected_hex: '预期响应前缀（十六进制）', protocol: '协议', hold_secs: '保持时长（秒）', tool: '执行工具', tool_version: '固定工具版本', max_hops: '最大跳数', reverse_server: '反向采集来源（可选）', client_mode: '客户端位置', receiver_server: '接收方服务器', receiver_host: '接收方监听 / 公布地址', direction: '发送方向', streams: '并行流数（分别保存）', duration_secs: '执行时长（秒）', rate_bps: '每流发送上限（bit/s）', latency_target: '负载延迟目标（可选）', threads: '线程数', block_bytes: '块大小（字节）', total_bytes: '总传输量（字节）', operation: '内存操作', directory: '允许的测试目录', file_bytes: '测试文件大小（字节）', queue_depth: '队列深度', mode: '读写模式', read_percent: '混合读取百分比', cpu_workers: 'CPU工作进程', memory_bytes: '内存工作量（字节）', io_workers: 'I/O工作进程', proxy_url: '服务器自有HTTP CONNECT代理（仅回环，可选）', discovery_url: '获准出口发现HTTPS接口', route_kind: '出口路径', address: '查询IP', provider_ids: '资料供应方ID（逗号分隔）', domain: '自有邮件域名', selector: 'DKIM选择器', ports: '服务端口（逗号分隔）', server_id: 'Speedtest站点ID（可选）', license_acknowledged: '我已确认工具许可与服务条款', major_version: 'Geekbench大版本（单独比较）', platform: '执行平台与环境', device: '只读健康设备（必须在清单中授权）' }
const selections: Record<string, string[]> = { family: ['ipv4', 'ipv6'], client_mode: ['managed', 'local'], record_type: ['A', 'AAAA', 'TXT', 'MX', 'NS', 'PTR', 'CNAME', 'SOA'], direction: ['forward', 'reverse', 'bidirectional'], tool: ['nexttrace', 'traceroute'], operation: ['read', 'write'], mode: ['read', 'write', 'randread', 'randwrite', 'randrw'], route_kind: ['nat_public', 'proxy_chain'] }
const budgetDefault: Budget = { duration_secs: 60, memory_bytes: 64 * 1024 * 1024, disk_bytes: 128 * 1024 * 1024, traffic_bytes: 256 * 1024 * 1024, rate_bps: 20_000_000, concurrency: 1, cpu_percent: 20, cpu_weight: 20, pause_on_service_error: true }
const emptyTarget = (): Target => ({ id: crypto.randomUUID(), name: '', host: '', region: '', carrier: '', purpose: '', authorization: '', authorized_until: null })
function defaults(kind: string, target: string): Check {
 const common = { kind, target_id: target, family: 'ipv4' }
 switch (kind) {
  case 'tcp': return { ...common, port: 443, samples: 4 }
  case 'icmp': return { ...common, samples: 4, packet_bytes: 56 }
  case 'http': return { ...common, url: 'https://example.com/', expected_status: 200, expected_content: null, follow_redirects: false }
  case 'dns': return { ...common, resolvers: ['127.0.0.1'], record_type: 'A', expected: [] }
  case 'tls': return { ...common, port: 443, server_name: 'example.com' }
  case 'udp': return { ...common, port: 53, protocol: 'dns', request_hex: '', expected_hex: '' }
  case 'quic': return { ...common, url: 'https://example.com/', tool_version: '', expected_status: 200 }
  case 'web_socket': return { ...common, url: 'wss://example.com/', hold_secs: 15 }
  case 'route': return { ...common, protocol: 'icmp', port: 443, tool: 'nexttrace', tool_version: '', max_hops: 20, reverse_server: null }
  case 'mtr': return { ...common, protocol: 'icmp', port: 443, tool_version: '', samples: 10 }
  case 'throughput': return { kind, client_mode: 'managed', receiver_server: 0, receiver_host: '', port: 5201, family: 'ipv4', direction: 'forward', protocol: 'tcp', streams: 1, duration_secs: 10, rate_bps: 20_000_000, tool_version: '', latency_target: null }
  case 'cpu': return { kind, tool_version: '', threads: 1, duration_secs: 10 }
  case 'memory': return { kind, tool_version: '', block_bytes: 1024 * 1024, total_bytes: 1024 * 1024 * 1024, operation: 'write' }
  case 'disk': return { kind, tool_version: '', directory: '/var/lib/sinan/diagnostic-tests', file_bytes: 64 * 1024 * 1024, block_bytes: 4096, queue_depth: 1, mode: 'randread', read_percent: 70, duration_secs: 10 }
  case 'stability': return { kind, tool_version: '', cpu_workers: 1, memory_bytes: 16 * 1024 * 1024, io_workers: 0, duration_secs: 15 }
  case 'hardware_info': return { kind, tool_version: '', device: '/dev/sda' }
  case 'exit': return { kind, family: 'ipv4', discovery_url: 'https://example.com/authorized-ip', route_kind: 'nat_public', proxy_url: null }
  case 'ip_info': return { kind, family: 'ipv4', address: '', provider_ids: [] }
  case 'mail': return { ...common, domain: 'example.com', selector: 'default', resolvers: ['127.0.0.1'], ports: [25, 587] }
  case 'geekbench_import': return { kind, tool_version: '', major_version: 6, platform: '' }
  case 'speedtest': return { kind, tool_version: '', server_id: null, license_acknowledged: false }
  default: return { kind }
 }
}
const time = (value: number) => new Date(value * 1000).toLocaleString('zh-CN', { timeZone: 'Asia/Taipei' })
function observation(result: Result): Record<string, unknown> | null {
 const value = result.observation
 if (!value) return null
 if (typeof value.text === 'string') { try { return JSON.parse(value.text) as Record<string, unknown> } catch { return value } }
 return (value.observation as Record<string, unknown> | undefined) ?? value
}
export default function NetworkWorkbench({ servers: suppliedServers, initialServerId }: { servers?: Server[]; initialServerId?: number }) {
 const [loadedServers, setLoadedServers] = useState<Server[]>([]), [serverListMessage, setServerListMessage] = useState('')
 const availableServers = suppliedServers ?? loadedServers
 const servers = initialServerId && !availableServers.some(server => server.id === initialServerId) ? [...availableServers, { id: initialServerId, name: `当前服务器 ${initialServerId}` }] : availableServers
 const [targets, setTargets] = useState<Target[]>([]), [tools, setTools] = useState<Tool[]>([]), [providers, setProviders] = useState<Provider[]>([]), [runs, setRuns] = useState<Run[]>([]), [plans, setPlans] = useState<SavedPlan[]>([])
 const [kind, setKind] = useState('tcp'), [check, setCheck] = useState<Check>(defaults('tcp', '')), [sourceKind, setSourceKind] = useState('server'), [selectedServers, setSelectedServers] = useState<number[]>(initialServerId ? [initialServerId] : [])
 const [targetFilters, setTargetFilters] = useState({region:'',carrier:'',purpose:''})
 const filteredTargets=targets.filter(target=>Object.entries(targetFilters).every(([key,query])=>target[key as 'region'|'carrier'|'purpose'].toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())))
 const [editingIndex, setEditingIndex] = useState<number | null>(null)
 const [steps, setSteps] = useState<Step[]>([]), [name, setName] = useState('自定义网络验机'), [budget, setBudget] = useState(budgetDefault), [schedule, setSchedule] = useState(false), [interval, setInterval] = useState(86400), [firstRun, setFirstRun] = useState(''), [missed, setMissed] = useState('skip')
 const [targetDraft, setTargetDraft] = useState(emptyTarget), [toolDraft, setToolDraft] = useState<Tool>({ id: 'iperf3', version: '', license: '', source_url: '', licensed: false, platforms: ['linux-amd64', 'linux-arm64'] })
 const [providerDraft, setProviderDraft] = useState<Provider>({ id: crypto.randomUUID(), name: '', endpoint: '', credential_ref: null, daily_quota: 100, cache_seconds: 3600, disabled: false })
 const [report, setReport] = useState<Report | null>(null), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [tab, setTab] = useState('plan'), [comparisonLeft, setComparisonLeft] = useState(''), [comparisonRight, setComparisonRight] = useState(''), [comparison, setComparison] = useState<unknown>(null), [importText, setImportText] = useState(''), [importIndex, setImportIndex] = useState(0), [importRole, setImportRole] = useState(''), [importSource, setImportSource] = useState(''), [license, setLicense] = useState(false)
 async function refresh() { const results = await Promise.all([api<Target[]>('/api/network-workbench/targets'), api<Tool[]>('/api/network-workbench/tools'), api<Provider[]>('/api/network-workbench/providers'), api<Run[]>('/api/network-workbench/runs'), api<SavedPlan[]>('/api/network-workbench/plans')]); setTargets(results[0]); setTools(results[1]); setProviders(results[2]); setRuns(results[3]); setPlans(results[4]) }
 useEffect(() => { void refresh().catch(e => setError(errorMessage(e))) }, [])
 useEffect(() => {
  if (suppliedServers !== undefined) return
  const controller = new AbortController()
  void api<{ role: string; capabilities: string[] }>('/api/control-center/me', 'GET', undefined, controller.signal).then(async actor => {
   if (actor.role !== 'owner' && !actor.capabilities.includes('servers:read')) {
    setServerListMessage('当前权限不包含服务器列表读取；可使用面板来源或当前服务器详情上下文。')
    return
   }
   const values = await api<Server[]>('/api/servers', 'GET', undefined, controller.signal)
   setLoadedServers(values)
   setServerListMessage(values.length ? '' : '当前没有可选择的授权服务器；可使用面板来源。')
  }).catch(e => { if (!controller.signal.aborted) setServerListMessage(`服务器列表未取得：${errorMessage(e)}`) })
  return () => controller.abort()
 }, [suppliedServers])
 useEffect(() => { if (initialServerId) setSelectedServers([initialServerId]) }, [initialServerId])
 useEffect(() => { if (targets.length && check.target_id === '') setCheck(value => ({ ...value, target_id: targets[0].id })) }, [targets, check.target_id])
 useEffect(() => { if (!report || !['queued', 'running', 'cleaning', 'cancel_requested'].includes(report.status)) return; const timer = window.setInterval(() => { void api<Report>(`/api/network-workbench/runs/${report.id}`).then(setReport).catch(e => setError(errorMessage(e))); void api<Run[]>('/api/network-workbench/runs').then(setRuns).catch(e => setError(errorMessage(e))) }, 5000); return () => window.clearInterval(timer) }, [report?.id, report?.status])
 async function action(task: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await task() } catch (e) { setError(errorMessage(e)) } finally { setBusy(false) } }
 const [submittedDraft, setSubmittedDraft] = useState('')
 const draftValue={name,budget,steps:steps.map(step=>({...step,check:Object.fromEntries(Object.entries(step.check).filter(([key])=>!['url','proxy_url','discovery_url','expected_content','request_hex','expected_hex'].includes(key))) as Check})),schedule,interval,firstRun,missed}
 const draftDirty=(steps.length>0 || name!=='自定义网络验机' || JSON.stringify(budget)!==JSON.stringify(budgetDefault)) && JSON.stringify(draftValue)!==submittedDraft
 const plan = (): Plan => ({ name, budget, steps, schedule: schedule ? { interval_secs: interval, first_run_at: Math.floor(new Date(firstRun).getTime() / 1000), timezone: 'Asia/Taipei', missed_window: missed } : null })
 function addStep() { const source: Source = sourceKind === 'panel' ? { kind: 'panel' } : sourceKind === 'group' ? { kind: 'group', server_ids: [...selectedServers] } : { kind: 'server', server_id: selectedServers[0] ?? 0 }; if (sourceKind !== 'panel' && selectedServers.length === 0) { setError('请选择固定的探测来源。'); return } setSteps(values => editingIndex == null ? [...values, { name: labels[kind], source, check, stop_on_failure: true }] : values.map((value, index) => index === editingIndex ? { ...value, source, check, name: labels[kind] } : value)); setEditingIndex(null) }
 function applyTemplate(checks: string[]) { const target = targets[0]; const source: Source = selectedServers.length ? { kind: 'server', server_id: selectedServers[0] } : { kind: 'server', server_id: 0 }; const versions: Record<string, string> = { cpu: 'sysbench', memory: 'sysbench', disk: 'fio', stability: 'stress-ng', route: 'nexttrace', mtr: 'mtr', throughput: 'iperf3', quic: 'curl' }; setSteps(checks.map(value => { const check = defaults(value, target?.id ?? ''); if (versions[value]) check.tool_version = tools.find(t => t.id === versions[value] && t.licensed)?.version ?? ''; if (target && value === 'tls') check.server_name = target.host; if (target && value === 'http') check.url = `https://${target.host.includes(':') ? `[${target.host}]` : target.host}/`; return { name: labels[value], source: value === 'ip_info' ? { kind: 'panel' as const } : source, check, stop_on_failure: true } })); setMessage('模板已载入草稿；请逐步补目标、工具、端点和授权，核对预算后提交。'); setEditingIndex(null) }
 function field(key: string, value: CheckValue) {
  const update = (next: CheckValue) => setCheck(previous => ({ ...previous, [key]: next }))
  if (key === 'target_id') return <label key={key}>{fieldLabels[key]}<select value={String(value)} onChange={e => update(e.target.value)}><option value="">选择获准目标</option>{targets.filter(target=>filteredTargets.includes(target)||target.id===String(value)).map(t => <option key={t.id} value={t.id}>{t.name} · {t.host} · {t.region} {t.carrier}</option>)}</select></label>
  if (key === 'receiver_server' || key === 'reverse_server') return <label key={key}>{fieldLabels[key]}<select value={value == null ? '' : String(value)} onChange={e => update(e.target.value ? Number(e.target.value) : null)}><option value="">请选择</option>{servers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
  if (typeof value === 'boolean') return <label key={key} className="nw-inline"><input type="checkbox" checked={value} onChange={e => update(e.target.checked)} />{fieldLabels[key]}</label>
  if (key === 'protocol') { const options = kind === 'throughput' ? ['tcp', 'udp'] : kind === 'udp' ? ['dns', 'echo', 'custom_authorized'] : ['icmp', 'tcp', 'udp']; return <label key={key}>{fieldLabels[key]}<select value={String(value)} onChange={e => update(e.target.value)}>{options.map(v => <option key={v}>{v}</option>)}</select></label> }
  if (selections[key]) return <label key={key}>{fieldLabels[key]}<select value={String(value)} onChange={e => update(e.target.value)}>{selections[key].map(v => <option key={v}>{v}</option>)}</select></label>
  if (Array.isArray(value)) return <label key={key}>{fieldLabels[key]}<input value={value.join(',')} onChange={e => update(key === 'ports' ? e.target.value.split(',').map(v => Number(v.trim())).filter(v => v > 0) : e.target.value.split(',').map(v => v.trim()).filter(Boolean))} /></label>
  const numeric = typeof value === 'number' || ['server_id', 'reverse_server'].includes(key)
  return <label key={key}>{fieldLabels[key] ?? key}<input type={numeric ? 'number' : 'text'} value={value == null ? '' : String(value)} onChange={e => update(e.target.value === '' && value === null ? null : numeric ? Number(e.target.value) : e.target.value)} /></label>
 }
 return <section className="network-workbench"><h2>网络检测与验机</h2><p>每个结果保留“从哪里测到哪里”、工具版本、参数和清理证据。完整NodeQuality仍受现有门禁约束。</p>
 {error && <p role="alert" className="error">{error}</p>}{message && <p role="status">{message}</p>}
 {tab === 'plan' && serverListMessage && <p role="status">{serverListMessage}</p>}
 <nav className="nw-tabs" aria-label="工作台视图">{[['plan', '测试方案'], ['targets', '授权目标'], ['tools', '工具与许可'], ['providers', 'IP资料来源'], ['reports', '任务与报告']].map(([value, text]) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{text}</button>)}</nav>
 {tab === 'plan' && <><FormDraftToolbar draftKey={`network-plan:${initialServerId ?? 'global'}`} value={draftValue} dirty={draftDirty} disabled={busy} description="保留来源、步骤和预算；URL、认证及请求正文需恢复后重新补齐，表单失败保持原输入。" onRestore={value=>{setName(value.name);setBudget({...budgetDefault,...value.budget});setSteps(value.steps.map(step=>({...step,check:{...defaults(step.check.kind,String(step.check.target_id ?? '')),...step.check}})));setSchedule(value.schedule);setInterval(value.interval);setFirstRun(value.firstRun);setMissed(value.missed);setEditingIndex(null)}} /><div className="nw-actions">{[['快速验机', ['tcp', 'tls', 'exit']], ['硬件验机', ['cpu', 'memory', 'disk']], ['网络验机', ['tcp', 'icmp', 'route', 'throughput']], ['出口检查', ['exit', 'ip_info', 'dns']], ['长期稳定性', ['stability', 'throughput']]].map(([label, checks]) => <button key={String(label)} onClick={() => applyTemplate(checks as string[])}>{String(label)}模板</button>)}</div><label>方案名称<input value={name} onChange={e => setName(e.target.value)} /></label><div className="nw-grid"><label>检查项目<select value={kind} onChange={e => { setKind(e.target.value); setCheck(defaults(e.target.value, targets[0]?.id ?? '')); if (e.target.value === 'ip_info') setSourceKind('panel') }}>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>探测来源<select value={sourceKind} onChange={e => setSourceKind(e.target.value)}><option value="panel">面板（TCP、HTTP、IP资料、本地配对）</option><option value="server">指定服务器</option><option value="group">服务器集合（提交后固定）</option></select></label>{sourceKind !== 'panel' && <label>来源服务器<select multiple={sourceKind === 'group'} value={sourceKind === 'group' ? selectedServers.map(String) : String(selectedServers[0] ?? '')} onChange={e => setSelectedServers(Array.from(e.target.selectedOptions).map(v => Number(v.value)))}>{sourceKind === 'server' && <option value="">请选择</option>}{servers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}{Object.entries(check).filter(([key]) => key !== 'kind').map(([key, value]) => field(key, value))}</div>
 {kind === 'node_quality_full' && <p role="alert">完整验机的离线受控工具链尚未签收，此项目无法启动。</p>}{kind === 'throughput' && <p>正向：来源发送、接收方接收；反向相反；双向同时记录两端。临时监听只在明确地址和预算内启动，等待真实监听证据后派发客户端。</p>}{kind === 'speedtest' && <p>Speedtest无法保证精确流量硬上限，因此受保护Agent拒绝直接执行。可导入按工具许可取得的原始报告。</p>}
 <button disabled={busy || kind === 'node_quality_full'} onClick={addStep}>{editingIndex == null ? '加入方案' : '保存步骤草稿'}</button><ol>{steps.map((step, index) => <li key={index}>{step.name} · {step.source.kind === 'panel' ? '面板' : step.source.kind === 'server' ? `服务器 ${step.source.server_id}` : `固定集合 ${step.source.server_ids.join(', ')}`} → {String(step.check.target_id ?? step.check.receiver_server ?? step.check.address ?? '本机资源')}<label className="nw-inline"><input type="checkbox" checked={step.stop_on_failure} onChange={e => setSteps(values => values.map((v, i) => i === index ? { ...v, stop_on_failure: e.target.checked } : v))} />失败终止后续步骤</label><button onClick={() => { setEditingIndex(index); setKind(step.check.kind); setCheck(step.check); setSourceKind(step.source.kind); setSelectedServers(step.source.kind === 'panel' ? [] : step.source.kind === 'server' ? [step.source.server_id] : step.source.server_ids) }}>编辑参数</button><button onClick={() => { setSteps(values => values.filter((_, i) => i !== index)); setEditingIndex(null) }}>移除</button></li>)}</ol>
 <details><summary>资源与业务保护预算</summary><div className="nw-grid">{Object.entries(budget).map(([key, value]) => typeof value === 'boolean' ? <label key={key}><input type="checkbox" checked={value} onChange={e => setBudget(v => ({ ...v, [key]: e.target.checked }))} />受管服务异常时停止</label> : <label key={key}>{({ duration_secs: '单步时长上限（秒）', memory_bytes: '内存上限（字节）', disk_bytes: '临时磁盘上限（字节）', traffic_bytes: '流量预算（字节）', rate_bps: '每流速率上限（bit/s）', concurrency: '并发来源', cpu_percent: 'CPU硬上限（一个逻辑核=100%）', cpu_weight: 'CPU争用权重（独立于硬上限）' } as Record<string, string>)[key]}<input type="number" value={value} onChange={e => setBudget(v => ({ ...v, [key]: Number(e.target.value) }))} /></label>)}</div></details>
 <label className="nw-inline"><input type="checkbox" checked={schedule} onChange={e => setSchedule(e.target.checked)} />定时复测（Asia/Taipei）</label>{schedule && <div className="nw-grid"><label>首次运行<input type="datetime-local" value={firstRun} onChange={e => setFirstRun(e.target.value)} /></label><label>间隔（秒）<input type="number" min={300} value={interval} onChange={e => setInterval(Number(e.target.value))} /></label><label>错过窗口<select value={missed} onChange={e => setMissed(e.target.value)}><option value="skip">跳过</option><option value="run_once">只补一次</option></select></label></div>}
 <div className="nw-actions"><button disabled={busy || !steps.length} onClick={() => void action(async () => { await api('/api/network-workbench/plans', 'POST', plan()); setSubmittedDraft(JSON.stringify(draftValue)); await refresh(); setMessage('方案已保存，来源集合及预算将在每次提交时固定。') })}>保存方案</button><button disabled={busy || !steps.length} onClick={() => { if (!window.confirm(`执行 ${steps.length} 个步骤，按已选预算产生网络流量或本机负载，是否提交？`)) return; void action(async () => { const run = await api<{ id: string }>('/api/network-workbench/runs', 'POST', plan()); setReport(await api<Report>(`/api/network-workbench/runs/${run.id}`)); setSubmittedDraft(JSON.stringify(draftValue)); setTab('reports'); await refresh() }) }}>预览后提交执行</button></div>
 <h3>保存的方案</h3>{plans.map(p => <div key={p.id}>{p.definition.plan.name} · 版本 {p.revision} · {p.enabled ? '计划已启用' : '手动执行'}<button onClick={() => { setName(p.definition.plan.name); setSteps(p.definition.plan.steps); setBudget({ ...budgetDefault, ...p.definition.plan.budget }) }}>载入草稿</button><button disabled={busy} onClick={() => void action(async () => { const result = await api<{ id: string }>(`/api/network-workbench/plans/${p.id}/run`, 'POST'); setReport(await api<Report>(`/api/network-workbench/runs/${result.id}`)); setTab('reports'); await refresh() })}>提交一次</button><button disabled={busy} onClick={() => void action(async () => { await api(`/api/network-workbench/plans/${p.id}`, 'PATCH', { plan: p.definition.plan, expected_revision: p.revision, enabled: !p.enabled }); await refresh() })}>{p.enabled ? '暂停计划' : '启用计划'}</button></div>)}</>}
 {tab === 'targets' && <><h3>自有或获准目标</h3><div className="nw-grid">{(['region','carrier','purpose'] as const).map(key=><label key={key}>{({region:'筛选地区',carrier:'筛选运营商',purpose:'筛选用途'})[key]}<input value={targetFilters[key]} onChange={event=>setTargetFilters(previous=>({...previous,[key]:event.target.value}))} /></label>)}</div><p>当前筛选 {filteredTargets.length} / {targets.length} 个获准目标；计划中的已选目标不会随筛选改变。</p><div className="nw-grid">{(['name', 'host', 'region', 'carrier', 'purpose', 'authorization'] as const).map(key => <label key={key}>{({ name: '名称', host: 'IP / 域名', region: '地区', carrier: '运营商', purpose: '用途', authorization: '自有或授权依据' })[key]}<input value={targetDraft[key]} onChange={e => setTargetDraft(v => ({ ...v, [key]: e.target.value }))} /></label>)}<label>授权截止时间<input type="datetime-local" onChange={e => setTargetDraft(v => ({ ...v, authorized_until: e.target.value ? Math.floor(new Date(e.target.value).getTime() / 1000) : null }))} /></label></div><button disabled={busy} onClick={() => void action(async () => { await api('/api/network-workbench/targets', 'POST', targetDraft); setTargetDraft(emptyTarget()); await refresh() })}>登记目标</button>{filteredTargets.map(t => <article key={t.id}><strong>{t.name}</strong> · {t.host} · {t.region} · {t.carrier}<p>{t.purpose} · {t.authorization} · {t.authorized_until ? time(t.authorized_until) : '持续授权'}</p><button disabled={busy} onClick={() => { if (window.confirm(`删除目标 ${t.name}？已提交方案保留目标快照。`)) void action(async () => { await api(`/api/network-workbench/targets/${t.id}`, 'DELETE'); await refresh() }) }}>移除目标</button></article>)}</>}
 {tab === 'tools' && <><p>执行前校对签名制品、离线工具摘要、固定版本、许可和平台。登记记录不代表工具已安装或实机验收已通过。</p><div className="nw-grid"><label>工具<select value={toolDraft.id} onChange={e => setToolDraft(v => ({ ...v, id: e.target.value }))}>{['nexttrace', 'traceroute', 'mtr', 'iperf3', 'sysbench', 'fio', 'stress-ng', 'speedtest', 'curl', 'smartctl', 'ping'].map(v => <option key={v}>{v}</option>)}</select></label>{(['version', 'license', 'source_url'] as const).map(key => <label key={key}>{({ version: '明确版本', license: '许可依据', source_url: '官方来源材料HTTPS地址' })[key]}<input value={toolDraft[key]} onChange={e => setToolDraft(v => ({ ...v, [key]: e.target.value }))} /></label>)}<label className="nw-inline"><input type="checkbox" checked={toolDraft.licensed} onChange={e => setToolDraft(v => ({ ...v, licensed: e.target.checked }))} />已满足许可条件</label></div><button disabled={busy} onClick={() => void action(async () => { await api('/api/network-workbench/tools', 'POST', toolDraft); await refresh() })}>登记工具供应</button>{tools.map(t => <p key={t.id}>{t.id} · {t.version} · {t.license} · {t.licensed ? '许可已确认' : '暂停执行'} · {t.platforms.join(', ')}</p>)}</>}
 {tab === 'providers' && <><p>逐供应方保留原始资料、时间、冲突与错误；资料标签不自动等于家宽或干净。凭据仅引用凭据中心条目。</p><div className="nw-grid">{(['name', 'endpoint', 'credential_ref'] as const).map(key => <label key={key}>{({ name: '资料源名称', endpoint: 'HTTPS接口（含 {ip}）', credential_ref: 'external-api凭据ID（可选）' })[key]}<input value={providerDraft[key] ?? ''} onChange={e => setProviderDraft(v => ({ ...v, [key]: key === 'credential_ref' ? e.target.value || null : e.target.value }))} /></label>)}<label>日配额<input type="number" value={providerDraft.daily_quota} onChange={e => setProviderDraft(v => ({ ...v, daily_quota: Number(e.target.value) }))} /></label><label>缓存（秒）<input type="number" value={providerDraft.cache_seconds} onChange={e => setProviderDraft(v => ({ ...v, cache_seconds: Number(e.target.value) }))} /></label></div><button disabled={busy} onClick={() => void action(async () => { await api('/api/network-workbench/providers', 'POST', providerDraft); await refresh(); setProviderDraft(v => ({ ...v, id: crypto.randomUUID() })) })}>登记资料源</button>{providers.map(p => <p key={p.id}>{p.name} · ID {p.id} · {p.daily_quota}次/日 · 缓存{p.cache_seconds}秒<button disabled={busy} onClick={() => void action(async () => { await api('/api/network-workbench/providers', 'POST', { ...p, disabled: !p.disabled }); await refresh() })}>{p.disabled ? '启用' : '停用'}</button></p>)}</>}
 {tab === 'reports' && <><button disabled={busy} onClick={() => void action(refresh)}>刷新任务</button><div className="nw-run-list">{runs.map(r => <button key={r.id} onClick={() => void action(async () => setReport(await api<Report>(`/api/network-workbench/runs/${r.id}`)))}>{r.name} · {r.status} · 第{r.current_step + 1}步 · {time(r.created_at)}</button>)}</div>
 {report && <article><h3>{report.snapshot.plan.name} · {report.status}</h3><p>{report.summary.step_count}个步骤 · {report.summary.result_count}份来源结果 · 成功{report.summary.succeeded} · 失败{report.summary.failed} · 等待清理{report.summary.cleanup_pending}</p>{report.error && <p role="alert">{report.error}</p>}<div className="nw-actions"><button disabled={busy || !['queued', 'running', 'paused', 'cleaning'].includes(report.status)} onClick={() => void action(async () => { await api(`/api/network-workbench/runs/${report.id}/cancel`, 'POST'); setReport(await api<Report>(`/api/network-workbench/runs/${report.id}`)) })}>请求取消并等待清理</button><button disabled={busy || report.status !== 'paused'} onClick={() => void action(async () => { await api(`/api/network-workbench/runs/${report.id}/resume`, 'POST'); setReport(await api<Report>(`/api/network-workbench/runs/${report.id}`)) })}>核对后继续</button><button disabled={busy} onClick={() => void action(async () => { const share = await api<{ path: string; id: string }>(`/api/network-workbench/runs/${report.id}/shares`, 'POST', { expires_at: Math.floor(Date.now() / 1000) + 3600, include_addresses: false }); setMessage(`脱敏报告分享（一小时）：${location.origin}${share.path}；撤销ID：${share.id}`) })}>生成一小时脱敏分享</button><button disabled={busy} onClick={() => void action(async () => { const selected = report.results.find(r => r.role === 'source:panel' && report.snapshot.plan.steps[r.step_index]?.check.kind === 'throughput'); if (!selected) throw new Error('本地配对方案需选择面板来源和local客户端。'); const pairing = await api<{ submit_path: string; instructions: string; execution: unknown }>('/api/network-workbench/pairings', 'POST', { run_id: report.id, step_index: selected.step_index, role: selected.role, expires_at: Math.floor(Date.now() / 1000) + 3600 }); setMessage(`本地提交地址：${location.origin}${pairing.submit_path}；${pairing.instructions} 参数：${JSON.stringify(pairing.execution)}`) })}>生成本地配对凭据</button><button onClick={() => { const data = URL.createObjectURL(new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = data; link.download = `network-report-${report.id}.json`; link.click(); URL.revokeObjectURL(data) }}>受控导出完整报告</button></div>
 <table><caption>固定来源—目标矩阵与分项结果</caption><thead><tr><th>步骤</th><th>来源</th><th>目标</th><th>结果</th><th>清理</th></tr></thead><tbody>{report.results.map(r => <tr key={r.id}><td>{r.step_index + 1} · {report.snapshot.plan.steps[r.step_index]?.name}</td><td>{r.source_server ? `服务器 ${r.source_server}` : '面板'} · {r.role}</td><td>{String(observation(r)?.target ?? '等待采集')}</td><td>{r.status}</td><td>{r.cleanup_origin === 'external_claim' ? '外部报告声明' : r.cleanup_confirmed ? '已确认' : '等待设备确认'}</td></tr>)}</tbody></table>
 {report.results.map(r => <details key={r.id}><summary>第{r.step_index + 1}步 · {r.role} · 参数、原始指标与环境</summary>{r.error && <p role="alert">{r.error}</p>}<PathView data={observation(r)?.data} /><ThroughputView observation={observation(r)} role={r.role} sourceServer={r.source_server} clientSource={(() => { const source = report.snapshot.plan.steps[r.step_index]?.source; return source?.kind === "server" ? `服务器 ${source.server_id}` : source?.kind === "group" && source.server_ids.length === 1 ? `服务器 ${source.server_ids[0]}` : source?.kind === "panel" ? "本地客户端" : undefined })()} /><pre>{JSON.stringify(observation(r), null, 2)}</pre>{r.sections.map(section => <details key={section.name}><summary>{section.name} · {section.complete ? '完整' : '部分'} · {time(section.collected_at)}</summary><pre>{section.text}</pre></details>)}</details>)}
 <details><summary>导入正式接口或获准外部报告</summary><p>报告必须有真实来源、工具版本、采集时间和与方案一致的参数，不能覆盖已派发设备任务。导入不代表实机签收。</p><div className="nw-grid"><label>步骤编号（从0起）<input type="number" value={importIndex} onChange={e => setImportIndex(Number(e.target.value))} /></label><label>来源角色<input value={importRole} onChange={e => setImportRole(e.target.value)} /></label><label>正式接口 / 授权报告来源<input value={importSource} onChange={e => setImportSource(e.target.value)} /></label><label><input type="checkbox" checked={license} onChange={e => setLicense(e.target.checked)} />报告来源与许可已确认</label></div><textarea aria-label="结构化Observation报告" value={importText} onChange={e => setImportText(e.target.value)} rows={8} /><button disabled={busy || !license} onClick={() => void action(async () => { await api(`/api/network-workbench/runs/${report.id}/import`, 'POST', { step_index: importIndex, role: importRole, authorized_source: importSource, license_acknowledged: license, observation: JSON.parse(importText) }); setReport(await api<Report>(`/api/network-workbench/runs/${report.id}`)) })}>核对并导入</button></details></article>}
 <details><summary>同条件历史比较与路径变更</summary><p>选择任务ID、步骤和来源；参数、工具版本或目标不同会明确拒绝统一分数。</p><div className="nw-grid"><label>左侧（任务ID,步骤,角色）<input value={comparisonLeft} onChange={e => setComparisonLeft(e.target.value)} /></label><label>右侧（任务ID,步骤,角色）<input value={comparisonRight} onChange={e => setComparisonRight(e.target.value)} /></label></div><button disabled={busy} onClick={() => void action(async () => { const [left_run, left_step, left_role] = comparisonLeft.split(','), [right_run, right_step, right_role] = comparisonRight.split(','); setComparison(await api('/api/network-workbench/compare', 'POST', { left_run, left_step: Number(left_step), left_role, right_run, right_step: Number(right_step), right_role })) })}>比较原始指标与路径跳变</button>{comparison != null && <pre>{JSON.stringify(comparison, null, 2)}</pre>}</details></>}
 </section>
}
