import { useEffect, useRef, useState } from 'react'
import { api, errorMessage } from '../api'
import { Badge, ErrorNotice, Field, Loading, PageHeader, Refresh } from '../components'
import { bytes } from '../format'
import { interfaceSelected } from '../display/data'
import { useResource } from '../hooks'
import type { Server } from '../types'
import FleetTerminal from './FleetTerminal'
import FleetTools from './FleetTools'
import FleetReconciliation from './FleetReconciliation'
import type { FleetPolicy, FleetProfile, OperationRecord } from './types'
import './fleet.css'
import FormDraftToolbar from '../control-center/FormDraftToolbar'
import { FleetPermissionsContext, fleetPermissions, useFleetPermissions } from './permissions'
import type { FleetActor } from './permissions'

const list = (value: FormDataEntryValue | null) => String(value ?? '').split(/[\n,]/).map(value => value.trim()).filter(Boolean)
const when = (value: number | null | undefined, millis = false) => value ? new Date(value * (millis ? 1 : 1000)).toLocaleString() : '未知'
const value = (entry: unknown) => entry === null || entry === undefined ? '未知' : typeof entry === 'object' ? JSON.stringify(entry) : String(entry)

export default function FleetOperations({serverId}: {serverId?: number}) {
  const actor = useResource<FleetActor>('/api/control-center/me')
  const permissions = fleetPermissions(actor)
  const servers = useResource<Server[]>('/api/servers'), [selected, setSelected] = useState(serverId ?? 0), [tab, setTab] = useState('overview')
  useEffect(() => setSelected(serverId ?? 0), [serverId])
  const current = selected || servers.data?.[0]?.id || 0
  const profile = useResource<FleetProfile>(current ? `/api/servers/${current}/fleet` : '/api/fleet/health')
  return <FleetPermissionsContext.Provider value={permissions}>
    <PageHeader eyebrow="服务器日常管理" title="服务器运维" description="接入模板、资产生命周期、资源归属和独立终端统一关联到所选服务器。"><Refresh onClick={() => {actor.reload();servers.reload(); profile.reload()}} /></PageHeader>
    <ErrorNotice message={actor.error || servers.error || profile.error} />
    <div className="fleet-controls"><Field label="当前服务器"><select value={current} onChange={event => {setSelected(Number(event.target.value)); setTab('overview')}}>{servers.data?.map(server => <option key={server.id} value={server.id}>{server.name}</option>)}</select></Field></div>
    <nav className="fleet-tabs">{[['overview','资源与能力'],['assets','资产与生命周期'],['tools','服务日志与文件'],['terminal','交互式终端'],['history','历史与比较'],['enrollment','模板与批量接入'],['health','面板健康']].map(([key,label]) => <button className={`button ${tab === key ? 'button-primary' : 'button-secondary'}`} key={key} onClick={() => setTab(key)}>{label}</button>)}</nav>
    {tab === 'enrollment' ? <Enrollment /> : tab === 'health' ? <Health /> : profile.loading || !profile.data || !current ? <Loading /> : <div key={current}>
      {tab === 'overview' && <Overview profile={profile.data} server={servers.data?.find(server => server.id === current)} />}
      {tab === 'assets' && <Assets profile={profile.data} servers={servers.data ?? []} reload={profile.reload} />}
      {tab === 'tools' && <FleetTools profile={profile.data} />}
      {tab === 'terminal' && <FleetTerminal profile={profile.data} />}
      {tab === 'history' && <History server={current} servers={servers.data ?? []} />}
    </div>}
  </FleetPermissionsContext.Provider>
}

function Overview({profile,server}: {profile:FleetProfile;server?:Server}) {
  const metrics = server?.latest_metrics as Record<string, unknown> | undefined
  const inventory = (metrics?.network_inventory ?? []) as Array<{name:string;physical:boolean;loopback:boolean;duplicate_risk:boolean}>
  const networkInterface = server?.asset_settings?.network_interface
  return <div className="fleet-grid"><section className="panel"><h2>数据可信状态</h2><Badge tone={server?.online && !server.metrics_stale ? 'good' : 'warm'}>{server?.metrics_stale ? '采样已过期' : server?.online ? '设备在线' : '设备离线或未接入'}</Badge><dl className="fleet-kv"><dt>最后采样</dt><dd>{when(profile.sampled_at,true)}</dd><dt>最后设备消息</dt><dd>{when(server?.last_seen)}</dd><dt>生命周期</dt><dd>{profile.lifecycle}</dd><dt>进程样本</dt><dd>{when(profile.processes?.sampled_at,true)}</dd></dl><p className="subtle">缺失与过期数据保留未知，历史比较不补零。</p><pre className="fleet-output">{JSON.stringify(profile.pressure ?? {state:'unknown',reason:'等待新版 Agent 压力采样'},null,2)}</pre></section>
    <section className="panel"><h2>能力清单</h2>{profile.capabilities.length ? <ul>{profile.capabilities.map(capability => <li key={capability}><code>{capability}</code></li>)}</ul> : <p>尚未收到设备能力。</p>}<p className="subtle">安装 Agent 后仍需按能力在设备本机和面板分别授权。终端与文件能力独立于旧远程命令。</p></section>
    <section className="panel"><h2>网卡参与统计与去重</h2><p>统计匹配：<code>{networkInterface === undefined ? '统计配置未知' : networkInterface || '当前配置包含全部网卡'}</code></p><div className="table-wrap"><table><thead><tr><th>网卡</th><th>观察分类</th><th>参与统计</th><th>注意</th></tr></thead><tbody>{inventory.map(item => <tr key={item.name}><td>{item.name}</td><td>{item.loopback ? '回环' : item.physical ? '物理关联' : '虚拟或未知'}</td><td>{networkInterface === undefined ? '未知' : interfaceSelected(item.name,networkInterface) ? '已计入' : '已排除'}</td><td>{item.duplicate_risk ? '可能重复，请明确排除' : '按统计匹配核对'}</td></tr>)}</tbody></table></div><p className="subtle">可在服务器费用与流量配置中指定网卡或排除模式。虚拟网卡分类不能证明所有网络拓扑。</p></section>
    <section className="panel"><h2>服务资源归属</h2>{profile.processes?.services_truncated&&<p className="subtle">已观测 {profile.processes.services_total} 个分组；受采样预算限制只展示部分分组，缺少分组不代表服务退出。</p>}<div className="table-wrap"><table><thead><tr><th>服务 / 控制组</th><th>CPU</th><th>内存</th><th>完整性</th></tr></thead><tbody>{profile.processes?.services.map(service => <tr key={service.name}><td>{service.name}</td><td>{service.cpu_percent === null ? '未知' : `${service.cpu_percent.toFixed(1)}%`}</td><td>{bytes(service.memory_bytes)}</td><td>{service.partial ? '仅部分进程' : '此组全部已观测进程'}</td></tr>)}</tbody></table></div></section>
    <section className="panel" style={{gridColumn:'1 / -1'}}><h2>进程资源</h2><p className="subtle">按 CPU 与内存排序，最多显示 64 个进程；CPU 可能超过 100%（多核）。磁盘差值为相邻采样间读写量。</p><div className="table-wrap"><table><thead><tr><th>PID / 名称</th><th>归属</th><th>CPU</th><th>内存</th><th>读取 / 写入</th></tr></thead><tbody>{profile.processes?.processes.map(process => <tr key={process.pid}><td>{process.pid} / {process.name}</td><td>{process.service || (process.container ? '容器' : '未归属')}</td><td>{process.cpu_percent === null ? '未知' : `${process.cpu_percent.toFixed(1)}%`}</td><td>{bytes(process.memory_bytes)}</td><td>{bytes(process.read_bytes_since_sample)} / {bytes(process.written_bytes_since_sample)}</td></tr>)}</tbody></table></div>{!profile.processes && <p>设备尚未提供进程采样。</p>}</section>
  </div>
}

function Assets({profile,servers,reload}: {profile:FleetProfile;servers:Server[];reload:()=>void}) {
  const permissions=useFleetPermissions(), canWrite=permissions.allows('servers:write',profile.server_id), canProfile=canWrite&&permissions.allows('security:write')
  const assetInputNames=['provider','cloud','region','order','note','cpu','memory','disk','bandwidth']
  const formRef=useRef<HTMLFormElement>(null)
  const [expectedDigest,setExpectedDigest]=useState(profile.digest), [dirty,setDirty]=useState(false), [assetDraft,setAssetDraft]=useState<Record<string,string>>(()=>Object.fromEntries([['provider','provider'],['cloud','cloud_account_reference'],['region','region'],['order','order_reference'],['note','note']].map(([name,key])=>[name,profile.asset[key]==null?'':value(profile.asset[key])]).concat([['cpu','cpu_cores'],['memory','memory_bytes'],['disk','disk_bytes'],['bandwidth','bandwidth_mbps']].map(([name,key])=>[name,String(profile.purchased[key]??'')]))))
  const readDraft=(form:HTMLFormElement)=>Object.fromEntries(assetInputNames.map(name=>[name,String(new FormData(form).get(name)??'')]))
  const restoreDraft=(draft:Record<string,string>)=>{for(const name of assetInputNames){const element=formRef.current?.elements.namedItem(name);if(element instanceof HTMLInputElement)element.value=draft[name]??''}setAssetDraft(draft);setDirty(true)}
  const costs = useResource<{records:Array<Record<string,unknown>>;annual:Array<{year:number;currency:string;amount_minor:string}>}>(`/api/servers/${profile.server_id}/fleet/costs`)
  const [error,setError] = useState(''), [busy,setBusy] = useState(false), [target,setTarget] = useState(0), [preview,setPreview] = useState<{confirmation:string;snapshot:unknown}|null>(null)
  const run = async (action:()=>Promise<unknown>,capability='servers:write',other?:number) => {const denied=permissions.reason(capability,profile.server_id)||(other?permissions.reason(capability,other):'');if(denied){setError(denied);return}setBusy(true);setError('');try {await action();reload();costs.reload()} catch (failure) {setError(errorMessage(failure))} finally {setBusy(false)}}
  const submit = (form:FormData) => {
    if(!permissions.allows('security:write')){setError(permissions.reason('security:write'));return}
    const purchased={...profile.purchased,cpu_cores:Number(form.get('cpu'))||null,memory_bytes:Number(form.get('memory'))||null,disk_bytes:Number(form.get('disk'))||null,bandwidth_mbps:Number(form.get('bandwidth'))||null}
    const asset={...profile.asset,provider:String(form.get('provider')),cloud_account_reference:String(form.get('cloud')),region:String(form.get('region')),order_reference:String(form.get('order')),note:String(form.get('note')),purchased}
    const policy:FleetPolicy={terminal_accounts:list(form.get('accounts')),services:list(form.get('services')),read_directories:list(form.get('read')),write_directories:list(form.get('write')),maximum_file_bytes:Number(form.get('maximum')),system_network:form.get('network')==='on',port_forward:form.get('forward')==='on',private_mesh:form.get('mesh')==='on',reverse_tunnel:form.get('tunnel')==='on',firewall:form.get('firewall')==='on',certificate_deploy:form.get('certificate')==='on',runtime_inspection:form.get('runtime_inspection')==='on'}
    void run(async()=>{const result=await api<{digest:string}>(`/api/servers/${profile.server_id}/fleet`,'PUT',{asset,policy,expected_digest:expectedDigest});setExpectedDigest(result.digest);setDirty(false)})
  }
  return <><ErrorNotice message={error || costs.error} /><div className="fleet-grid"><section className="panel"><h2>采购配置与实际观测</h2>{!canProfile&&<p className="fleet-warning">{permissions.reason('servers:write',profile.server_id)||permissions.reason('security:write')}资产与授权保存需两项权限。</p>}<table><thead><tr><th>指标</th><th>购买记录</th><th>实际观测</th></tr></thead><tbody>{[['cpu_cores','CPU 线程'],['memory_bytes','内存字节'],['disk_bytes','磁盘字节'],['bandwidth_mbps','带宽 Mbps']].map(([key,label])=><tr key={key}><td>{label}</td><td>{value(profile.purchased[key])}</td><td>{value(profile.observed[key])}</td></tr>)}</tbody></table><p className="subtle">带宽购买值与测速结果不同，未观测的配置保持未知。</p><FormDraftToolbar draftKey={`fleet-assets:${profile.server_id}`} value={assetDraft} dirty={dirty} disabled={busy||!canProfile} onRestore={restoreDraft} description="草稿只保存采购与资产输入；受限运维授权需单独核对。失败保留当前内容。" />{expectedDigest!==profile.digest&&<p role="alert">远端资产或授权已变化。保存当前草稿后，<button type="button" onClick={()=>{if(!dirty||window.confirm('用已读取的远端资料替换当前输入？')){formRef.current?.reset();if(formRef.current)setAssetDraft(readDraft(formRef.current));setExpectedDigest(profile.digest);setDirty(false)}}}>重新载入远端版本</button>，再确认差异。</p>}<form ref={formRef} onChange={()=>{setDirty(true);if(formRef.current)setAssetDraft(readDraft(formRef.current))}} onSubmit={event=>{event.preventDefault();submit(new FormData(event.currentTarget))}}><fieldset disabled={busy||!canProfile}><div className="fleet-controls">{[['provider','供应商'],['cloud','云账号参考'],['region','地区'],['order','订单参考'],['note','备注']].map(([key,label])=><Field key={key} label={label}><input name={key} defaultValue={value(profile.asset[key==='cloud'?'cloud_account_reference':key==='order'?'order_reference':key])==='未知'?'':value(profile.asset[key==='cloud'?'cloud_account_reference':key==='order'?'order_reference':key])} /></Field>)}</div><div className="fleet-controls">{[['cpu','CPU线程','cpu_cores'],['memory','内存字节','memory_bytes'],['disk','磁盘字节','disk_bytes'],['bandwidth','带宽 Mbps','bandwidth_mbps']].map(([name,label,key])=><Field key={name} label={label}><input type="number" min={0} name={name} defaultValue={String(profile.purchased[key]??'')} /></Field>)}</div>
      <h3>受限运维授权</h3><Field label="终端账号（逗号分隔）"><input name="accounts" defaultValue={profile.policy.terminal_accounts.join(',')} /></Field><Field label="服务（逗号分隔）"><input name="services" defaultValue={profile.policy.services.join(',')} /></Field><Field label="只读目录（每行一个）"><textarea name="read" defaultValue={profile.policy.read_directories.join('\n')} /></Field><Field label="允许保存目录（每行一个）"><textarea name="write" defaultValue={profile.policy.write_directories.join('\n')} /></Field><Field label="文件大小上限（字节）"><input name="maximum" type="number" min={1} max={262144} defaultValue={profile.policy.maximum_file_bytes||262144} /></Field><label><input type="checkbox" name="network" defaultChecked={profile.policy.system_network} />授权系统网络调优</label><label><input type="checkbox" name="forward" defaultChecked={profile.policy.port_forward} />授权受管端口转发</label><label><input type="checkbox" name="mesh" defaultChecked={profile.policy.private_mesh} />授权私有组网</label><label><input type="checkbox" name="tunnel" defaultChecked={profile.policy.reverse_tunnel} />授权反向隧道</label><label><input type="checkbox" name="firewall" defaultChecked={profile.policy.firewall} />授权受管防火墙</label><label><input type="checkbox" name="certificate" defaultChecked={profile.policy.certificate_deploy} />授权专用证书部署</label><label><input type="checkbox" name="runtime_inspection" defaultChecked={profile.policy.runtime_inspection} />授权运行时目录与服务权限只读预检</label><p className="subtle">面板授权还须与 Agent 本机允许范围相符；调整授权需要近期身份验证。</p><button className="button button-primary" disabled={busy||!canProfile}>保存资产与授权</button></fieldset></form></section>
      <section className="panel"><h2>维护与停止接收新任务</h2>{!canWrite&&<p className="fleet-warning">{permissions.reason('servers:write',profile.server_id)}</p>}<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(()=>api(`/api/servers/${profile.server_id}/fleet/lifecycle`,'POST',{lifecycle:String(form.get('lifecycle')),from:form.get('from')?Math.floor(new Date(String(form.get('from'))).getTime()/1000):null,until:form.get('until')?Math.floor(new Date(String(form.get('until'))).getTime()/1000):null,reason:String(form.get('reason'))}))}}><fieldset disabled={busy||!canWrite}><Field label="状态"><select name="lifecycle" defaultValue={profile.lifecycle}><option value="active">正常接收任务</option><option value="maintenance">维护窗口</option><option value="draining">停止接收新任务</option></select></Field><Field label="开始时间（空白立即）"><input name="from" type="datetime-local" /></Field><Field label="结束时间（空白无限期）"><input name="until" type="datetime-local" /></Field><Field label="原因"><input name="reason" defaultValue={profile.maintenance_reason??''} /></Field><button className="button button-primary" disabled={busy}>应用生命周期</button></fieldset></form><p className="subtle">维护保留监测数据并抑制通知，停止新命令和诊断。已有执行不会被当成停止。退役需回服务器列表确认关联服务，并完成设备清理确认。</p><pre className="fleet-output">{JSON.stringify(profile.related,null,2)}</pre>
      <h3>迁移采集配置</h3><Field label="新服务器"><select value={target} disabled={busy} onChange={event=>{setTarget(Number(event.target.value));setPreview(null)}}><option value={0}>选择目标</option>{servers.filter(server=>server.id!==profile.server_id).map(server=><option key={server.id} value={server.id}>{server.name}</option>)}</select></Field><div className="fleet-controls"><button className="button button-secondary" disabled={!target||busy||!permissions.allows('servers:read',profile.server_id)||!permissions.allows('servers:read',target)} onClick={()=>void run(async()=>setPreview(await api(`/api/servers/${profile.server_id}/fleet/migration-preview`,'POST',{target_server_id:target})),'servers:read',target)}>预览影响</button><button className="button button-primary" disabled={!preview||busy||!canWrite||!permissions.allows('servers:write',target)} onClick={()=>void run(()=>api(`/api/servers/${profile.server_id}/fleet/migrate`,'POST',{target_server_id:target,confirmation:preview?.confirmation}),'servers:write',target)}>确认迁移采集配置</button></div>{preview&&<pre className="fleet-output">{JSON.stringify(preview.snapshot,null,2)}</pre>}<p className="subtle">重新生成拨测身份，保留目标独立 Agent 身份；代理业务需通过插件迁移助手确认。</p></section>
      <section className="panel"><h2>续费与年度成本</h2>{!canWrite&&<p className="fleet-warning">{permissions.reason('servers:write',profile.server_id)}</p>}<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(()=>api(`/api/servers/${profile.server_id}/fleet/costs`,'POST',{kind:String(form.get('kind')),amount_minor:Number(form.get('amount')),currency:String(form.get('currency')),occurred_at:Math.floor(Date.now()/1000),valid_until:form.get('until')?Math.floor(new Date(String(form.get('until'))).getTime()/1000):null,reference:String(form.get('reference'))}))}}><fieldset disabled={busy||!canWrite}><Field label="记录类型"><select name="kind"><option value="renewal">续费</option><option value="purchase">购买</option><option value="price_change">价格变化</option><option value="refund">退款</option><option value="cancellation">退订</option></select></Field><Field label="金额（最小货币单位，如分）"><input name="amount" type="number" min={0} required /></Field><Field label="币种"><input name="currency" defaultValue="CNY" maxLength={3} required /></Field><Field label="到期 / 计划退订日期（依记录类型）"><input name="until" type="datetime-local" /></Field><Field label="订单 / 备注"><input name="reference" /></Field><button className="button button-primary" disabled={busy}>记录费用</button></fieldset></form><h3>各年原币汇总</h3>{costs.data?.annual.map(row=><p key={`${row.year}-${row.currency}`}>{row.year} · {row.currency} · {row.amount_minor} 最小货币单位</p>)}<details><summary>费用历史</summary><pre className="fleet-output">{JSON.stringify(costs.data?.records??[],null,2)}</pre></details></section>
    </div></>
}

function Enrollment() {
  const permissions=useFleetPermissions(), canWrite=permissions.allows('servers:write','global')
  const templates=useResource<Array<{id:string;name:string;config:unknown}>>(permissions.allows('servers:read','global')?'/api/fleet/templates':null)
  const [template,setTemplate]=useState(''),[name,setName]=useState(''),[names,setNames]=useState(''),[config,setConfig]=useState('{"asset_settings":{"group_name":"默认分组","tags":[]},"agent_settings":{"sample_interval_secs":1,"upload_interval_secs":3,"auto_update":false,"discover_public_ips":true},"telemetry_settings":{"persist_interval_secs":60},"probes":[],"alerts":[],"asset":{}}'),[result,setResult]=useState<unknown>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const run=async(action:()=>Promise<unknown>)=>{const denied=permissions.reason('servers:write','global');if(denied){setError(denied);return}setBusy(true);setError('');try{setResult(await action());templates.reload()}catch(failure){setError(errorMessage(failure))}finally{setBusy(false)}}
  return <><ErrorNotice message={error||templates.error}/><div className="fleet-grid"><section className="panel"><h2>接入模板</h2>{!canWrite&&<p className="fleet-warning">{permissions.reason('servers:write','global')}</p>}<Field label="选择已有模板"><select value={template} onChange={event=>{setTemplate(event.target.value);const item=templates.data?.find(item=>item.id===event.target.value);if(item){setName(item.name);setConfig(JSON.stringify(item.config,null,2))}}}><option value="">新模板</option>{templates.data?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="模板名称"><input value={name} readOnly={!canWrite} onChange={event=>setName(event.target.value)}/></Field><Field label="分组、标签、监测、告警与采集配置"><textarea className="fleet-editor" value={config} readOnly={!canWrite} onChange={event=>setConfig(event.target.value)}/></Field><button className="button button-primary" disabled={busy||!canWrite||!name} onClick={()=>void run(()=>api('/api/fleet/templates','POST',{id:template||undefined,name,config:JSON.parse(config)}))}>保存模板</button></section><section className="panel"><h2>批量登记</h2><Field label="每行一个服务器名称（最多 100 台）"><textarea className="fleet-editor" value={names} readOnly={!canWrite} onChange={event=>setNames(event.target.value)}/></Field><p className="subtle">每台分别登记并生成一次性独立凭据，有效期 24 小时。登记成功与设备已接入分别展示；安装命令仍从服务器接入页生成。</p><button className="button button-primary" disabled={busy||!canWrite||!names.trim()} onClick={()=>void run(()=>api('/api/fleet/batch-enrollment','POST',{template_id:template||undefined,names:names.split('\n').map(name=>name.trim()).filter(Boolean)}))}>按模板批量登记</button><pre className="fleet-output">{result?JSON.stringify(result,null,2):'凭据仅在本次响应中显示，请妥善保存。'}</pre></section></div></>
}

function History({server,servers}: {server:number;servers:Server[]}) {
  const permissions=useFleetPermissions()
  const events=useResource<unknown[]>(`/api/servers/${server}/fleet/events`),operations=useResource<OperationRecord[]>(permissions.allows('operations:read',server)?`/api/servers/${server}/fleet/operations`:null)
  const [other,setOther]=useState(server),[metric,setMetric]=useState('cpu_percent'),[comparison,setComparison]=useState<unknown>(null),[error,setError]=useState('')
  return <><ErrorNotice message={error||events.error||operations.error}/><div className="fleet-grid"><section className="panel"><h2>昨日与今日 / 服务器比较</h2><Field label="对照服务器"><select value={other} onChange={event=>setOther(Number(event.target.value))}>{servers.map(server=><option key={server.id} value={server.id}>{server.name}</option>)}</select></Field><Field label="同指标"><select value={metric} onChange={event=>setMetric(event.target.value)}>{[['cpu_percent','CPU'],['memory_used','内存'],['disk_used','磁盘'],['swap_used','交换空间'],['load_1','系统负载']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><button className="button button-secondary" disabled={!permissions.allows('monitoring:read',server)||!permissions.allows('monitoring:read',other)} onClick={()=>{if(!permissions.allows('monitoring:read',server)||!permissions.allows('monitoring:read',other))return;const until=Math.floor(Date.now()/1000),from=until-86400;void api(`/api/servers/${server}/fleet/compare?server_id=${other}&from=${from}&until=${until}&metric=${metric}`).then(setComparison).catch(failure=>setError(errorMessage(failure)))}}>比较最近 24 小时与此前 24 小时</button><pre className="fleet-output">{JSON.stringify(comparison??{missing:'缺失时间段不补零'},null,2)}</pre></section><section className="panel"><h2>异常与变更时间线</h2><pre className="fleet-output">{JSON.stringify(events.data??[],null,2)}</pre></section><section className="panel"><h2>操作历史</h2>{!permissions.allows('operations:read',server)&&<p className="fleet-warning">{permissions.reason('operations:read',server)}</p>}<div className="table-wrap"><table><thead><tr><th>项目</th><th>状态</th><th>发起时间</th></tr></thead><tbody>{operations.data?.map(operation=><tr key={operation.id}><td>{operation.operation?.kind}</td><td>{operation.status}</td><td>{when(operation.requested_at)}</td></tr>)}</tbody></table></div><p className="subtle">请求已交付后发生超时会保留未知结果，不能自动重复副作用动作。</p><details><summary>人工核对记录</summary><pre className="fleet-output">{JSON.stringify(operations.data?.filter(operation=>operation.reconciliation)??[],null,2)}</pre></details></section><FleetReconciliation server={server} operations={operations.data??[]} reload={operations.reload}/></div></>
}
function Health(){const resource=useResource<unknown>('/api/fleet/health');return <section className="panel"><h2>面板自身监控</h2><ErrorNotice message={resource.error}/><p className="subtle">数据库、任务积压和通知投递可核对。宿主磁盘容量、实际执行器心跳、备份和签名制品状态在系统自检页集中查看；独立观察点可提交健康证据。</p><a className="button button-secondary" href="#/control-center">打开系统自检与安全中心</a><pre className="fleet-output">{JSON.stringify(resource.data??{},null,2)}</pre></section>}
