import { api } from '../api'
import { ErrorNotice, Loading, Refresh } from '../components'
import { useAction, useResource } from '../hooks'

type Worker = { name: string; status: string; observed_at: number | null; last_success_at?: number | null; details?: unknown; reason?: string }
type Observer = { observer_name: string; target_origin: string; observed_at: number; received_at: number; available: boolean | null; elapsed_ms: number | null; evidence: unknown }
type Backup = { id: string; name: string; created_at: number; encrypted: boolean; verification: string; last_drill: { passed: boolean; recorded_at: number; action: string } | null }
type Schedule = { id: string; name: string; paused: boolean; next_run_at: number; last_started_at: number | null; last_finished_at: number | null; last_error: string | null }
type Health = { version: string; sampled_at: number; uptime_seconds: number; database: { available: boolean; elapsed_ms: number; bytes: number; pool_size: number; idle: number }; disk: { status: string; available_bytes?: number; total_bytes?: number; used_bytes?: number; observed_at?: number; reason?: string; raw?: string }; backlog: Record<string, number>; workers: Worker[]; independent_observers: Observer[]; backup: { status: string; latest: Backup | null; schedules: Schedule[] }; update: { status: string; observed_at?: number; source?: string; reason?: string; remote_checked: boolean; entries?: Array<{ name: string; version: string; arch: string; sha256: string }> } }
const time = (value: number | null | undefined) => value ? new Date(value * 1000).toLocaleString('zh-CN') : '暂无观察'
const bytes = (value: number | undefined) => value === undefined ? '未知' : value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(2)} GiB` : `${(value / 1024 ** 2).toFixed(1)} MiB`
const statusNames: Record<string, string> = { healthy: '周期成功', running: '执行中', failed: '周期失败', stale: '观察已过期', unknown: '未知', observed: '已观察', recorded: '已有记录' }
const workerNames: Record<string, string> = { maintenance: '面板维护', 'telemetry-history': '监控历史', 'control-center': '记录清理', 'network-workbench': '检测计划', operations: '批量运维', 'operations-backups': '定时备份', 'network-certificates': '证书续期', ddns: 'DNS 同步', alicloud: '云资源同步', 'alicloud-cost-cache': '云费用缓存', 'alicloud-power': '云启停计划', 'sing-box': '代理业务' }
const kindNames: Record<string, string> = { monitoring: '监控', logs: '日志', ip: 'IP 查询', terminal: '终端', 'proxy-access': '代理访问', audit: '审计' }
const queueNames: Record<string, string> = { commands: '远程命令', diagnostics: '诊断任务', notifications: '通知投递', fleet: '日常运维', operations: '批量计划' }
const verificationNames: Record<string, string> = { declared: '仅登记清单', integrity_verified: '完整性已核对', restored: '曾通过隔离恢复' }
export default function SystemHealth() {
  const resource = useResource<Health>('/api/control-center/health')
  const retention = useResource<Array<{ kind: string; days: number }>>('/api/control-center/retention')
  const action = useAction()
  const health = resource.data
  return <><section className="panel"><div className="panel-heading"><h2>系统自检</h2><Refresh onClick={resource.reload} /></div><div className="panel-body"><ErrorNotice message={resource.error} retry={resource.reload} />{resource.loading && !health && <Loading />}{health && <>
    <p>面板 {health.version} · 采样 {time(health.sampled_at)} · 运行 {Math.floor(health.uptime_seconds / 60)} 分钟</p>
    <div className="health-summary"><div><strong>数据库</strong><p>{health.database.available ? '连接成功' : '连接不可用'} · {health.database.elapsed_ms} ms</p><small>{bytes(health.database.bytes)} · 连接 {health.database.pool_size}，空闲 {health.database.idle}</small></div><div><strong>存储空间</strong><p>{health.disk.status === 'observed' ? `可用 ${bytes(health.disk.available_bytes)}` : '容量未知'}</p><small>{health.disk.reason ?? `总容量 ${bytes(health.disk.total_bytes)} · 使用 ${bytes(health.disk.used_bytes)}`}</small></div></div>
    <h3>任务与通知</h3><div className="health-queues">{Object.entries(health.backlog).map(([kind, count]) => <div key={kind}><span>{queueNames[kind] ?? kind}</span><strong>{count}</strong></div>)}</div><p>数量包含待执行、执行中或待核对任务；未知结果不会自动重试。</p>
    <h3>后台执行器</h3><div className="health-workers">{health.workers.map(worker => <details key={worker.name}><summary><strong>{workerNames[worker.name] ?? worker.name}</strong><span data-health={worker.status}>{statusNames[worker.status] ?? worker.status}</span></summary><p>观察 {time(worker.observed_at)} · 最近成功 {time(worker.last_success_at)}</p>{worker.reason && <p>{worker.reason}</p>}{worker.details !== undefined && <pre>{JSON.stringify(worker.details, null, 2)}</pre>}</details>)}</div>
    <h3>备份与恢复</h3>{health.backup.latest ? <div><strong>{health.backup.latest.name}</strong><p>{time(health.backup.latest.created_at)} · {health.backup.latest.encrypted ? '加密存储' : '未声明加密'} · {verificationNames[health.backup.latest.verification] ?? health.backup.latest.verification}</p><p>{health.backup.latest.last_drill ? `最近${health.backup.latest.last_drill.action === 'verify' ? '完整性核对' : '隔离恢复'} ${health.backup.latest.last_drill.passed ? '通过' : '失败'} · ${time(health.backup.latest.last_drill.recorded_at)}` : '尚无恢复检查记录'}</p></div> : <p>尚无可用备份记录。</p>}{health.backup.schedules.map(schedule => <div className="control-row" key={schedule.id}><span>{schedule.name} · {schedule.paused ? '已暂停' : `下次 ${time(schedule.next_run_at)}`}<small> · 上次完成 {time(schedule.last_finished_at)}</small></span>{schedule.last_error && <span role="alert">{schedule.last_error}</span>}</div>)}<a href="#/operations">打开备份与隔离恢复记录</a>
    <h3>版本与外部依赖</h3><p>{health.update.status === 'observed' ? `本地签名制品已读取 · ${time(health.update.observed_at)}` : health.update.reason ?? '制品状态未知'}。本次未查询外部发布源。</p>{health.update.entries?.map(entry => <details key={`${entry.name}-${entry.version}-${entry.arch}`}><summary>{entry.name} · {entry.version} · {entry.arch}</summary><code>{entry.sha256}</code></details>)}
    <h3>独立观察点</h3>{health.independent_observers.length === 0 && <p>尚未收到独立观察点证据。</p>}{health.independent_observers.map((observer, index) => { const stale = health.sampled_at - observer.observed_at > 120; return <details key={`${observer.observer_name}-${observer.observed_at}-${index}`}><summary>{observer.observer_name} · {stale ? '观察已过期' : observer.available === true ? '可访问' : observer.available === false ? '访问失败' : '结果未知'}</summary><p>{observer.target_origin} · 观察 {time(observer.observed_at)} · 接收 {time(observer.received_at)} · {observer.elapsed_ms ?? '未知'} ms</p><pre>{JSON.stringify(observer.evidence, null, 2)}</pre></details> })}
  </>}<p>状态来自实际采样、后台周期及独立提交的证据；未观察或过期状态保持未知。</p></div></section>
  <section className="panel"><div className="panel-heading"><h2>分类保留期限</h2></div><div className="panel-body"><ErrorNotice message={retention.error || action.error} retry={retention.reload} />{retention.data?.map(policy => <form className="control-row" key={`${policy.kind}-${policy.days}`} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void action.run(() => api(`/api/control-center/retention/${policy.kind}`, 'PUT', { days: Number(data.get('days')) }), retention.reload) }}><span>{kindNames[policy.kind] ?? policy.kind}</span><label><input aria-label={`${kindNames[policy.kind] ?? policy.kind}保留天数`} name="days" type="number" min={1} max={3650} defaultValue={policy.days} /> 天</label><button disabled={action.busy}>保存期限</button></form>)}</div></section></>
}
