import { useState } from 'react'
import { api } from '../../api'
import { Badge, ErrorNotice, Field, Loading, Refresh } from '../../components'
import { time } from '../../format'
import { resourceWriteError, useAction, useResource } from '../../hooks'
import type { Node, PluginServer } from '../../types'
import type { PolicyGroup, ProxyResource } from './groupTypes'
import OperationReview from './OperationReview'
import DeploymentPreflight from './DeploymentPreflight'
import type { DeploymentPreflightState } from './DeploymentPreflight'
import type { WorkflowOperation } from './OperationReview'

type View = {
  runtime: { supported_versions: string[]; selected_version: string; reason: string; compatibility_metadata: { upstream_release: string; upstream_commit: string; protocols: string[]; acceptance_scope: string } }
  preflight: DeploymentPreflightState
  drift: { state: string; target_revision: number | null; applied_revision: number | null; last_observed_at: number | null; reason: string; checkpoint_supported: boolean; checkpoint: { state: string; observed_at?: number | null; reason: string } }
  changes: { node_id: number; change: string; before: { name: string; public_host: string; port: number; user_ids: number[] } | null; after: { name: string; public_host: string; port: number; user_ids: number[] } | null; affected_users: number[] }[]
  history: { revision: number; created_at: number; runtime_version: string | null; artifact_sha256: string | null }[]
  paths: { id: number; name: string; phase: string; desired_generation: number; applied_generation: number | null; candidate_generation: number | null; last_error: string | null }[]
  hop_observations: { server_id: number; name: string; last_seen: number | null; healthy: boolean | null; target_revision: number | null; applied_revision: number | null }[]
  path_diagnosis: string
}
const driftNames: Record<string, string> = { needs_preflight: '新监听或部署配置等待完整预检确认', stale: '设备离线，旧证据过期', pending_publish: '业务配置等待发布', unknown: '尚无配置证据', revision_mismatch: '运行版本与目标不同', unhealthy: '健康状态待处理', revision_aligned: '已回报版本一致', configuration_mismatch: '发现配置或运行进程偏差', configuration_verified: '实际配置与进程已核对', inspection_pending: '等待实际配置核对' }

export default function OperationsWorkflows({ serverId }: { serverId: number }) {
  const resource = useResource<View>(`/api/plugins/sing-box/servers/${serverId}/operations-view`)
  const [editing, setEditing] = useState(false)
  const action = useAction()
  const [inspectionNotice, setInspectionNotice] = useState('')
  const current = resource.data
  return <section className="runtime-operations"><div className="panel-heading"><h3>配置预检、差异与链路证据</h3><Refresh onClick={resource.reload} /></div><ErrorNotice message={resource.error || action.error} retry={resource.reload} />
    {!current ? <Loading /> : <>
      <p>运行时版本：{current.runtime.selected_version}。{current.runtime.reason}</p><p className="helper"><a href={current.runtime.compatibility_metadata.upstream_release} target="_blank" rel="noreferrer">官方版本材料</a> · 固定上游提交 {current.runtime.compatibility_metadata.upstream_commit.slice(0, 12)}；{current.runtime.compatibility_metadata.acceptance_scope}。</p>
      <p><Badge tone={current.drift.state === 'revision_aligned' ? 'good' : 'warm'}>{driftNames[current.drift.state] ?? '状态未知'}</Badge> 目标 {current.drift.target_revision ?? '—'} / 已应用 {current.drift.applied_revision ?? '—'} · 观测 {current.drift.last_observed_at ? time(current.drift.last_observed_at) : '未提供'}</p><p className="helper">{current.drift.reason}</p>
      <p>{current.drift.checkpoint.reason}{current.drift.checkpoint.observed_at ? ` · 核对于 ${time(current.drift.checkpoint.observed_at)}` : ''}</p><button className="button button-secondary button-small" disabled={action.busy || Boolean(resourceWriteError(resource)) || !current.drift.checkpoint_supported || ['inspection_pending', 'pending_publish', 'needs_preflight', 'stale', 'unknown'].includes(current.drift.state)} onClick={() => void action.run(() => api(`/api/plugins/sing-box/servers/${serverId}/operations-view/checkpoint`, 'POST'), () => { setInspectionNotice('已请求目标 Agent 核对实际配置文件、签名运行时和受管进程；等待回执。'); resource.reload() })}>主动核对实际配置与进程</button>{!current.drift.checkpoint_supported && <p className="helper">此 Agent 尚未声明实际配置核对能力，请先升级。</p>}{inspectionNotice && <p role="status">{inspectionNotice}</p>}
      <DeploymentPreflight serverId={serverId} current={current.preflight} unavailable={Boolean(resourceWriteError(resource))} reload={resource.reload} />
      <details><summary>业务目标与上次应用的节点差异（{current.changes.length} 项）</summary><p>按节点与关联用户显示，敏感值隐藏；链路代数和候选状态在下方分别核对。列表变更尚未表示设备应用成功。</p><div className="table-wrap"><table><thead><tr><th>节点</th><th>变化</th><th>应用前 / 业务目标</th><th>影响用户</th></tr></thead><tbody>{current.changes.map(change => <tr key={change.node_id}><td>{change.after?.name ?? change.before?.name ?? `#${change.node_id}`}</td><td>{change.change === 'added' ? '新增' : change.change === 'removed' ? '移除' : '参数或凭据变化'}</td><td>{change.before ? `${change.before.public_host}:${change.before.port}` : '无'} → {change.after ? `${change.after.public_host}:${change.after.port}` : '无'}</td><td>{change.affected_users.join('、') || '无有效用户'}</td></tr>)}</tbody></table></div></details>
      {current.paths.length > 0 && <><h4>链路候选与切换确认</h4>{current.paths.map(path => <p key={path.id}><a href="#/plugins/sing-box/nodes">{path.name}</a> · 目标代数 {path.desired_generation} / 应用 {path.applied_generation ?? '—'} / 候选 {path.candidate_generation ?? '无'} · {path.phase === 'applied' ? '已应用' : path.candidate_generation ? '候选流程进行中' : '查看节点页阶段'}{path.last_error ? `；${path.last_error}` : ''}</p>)}<p>{current.path_diagnosis}</p><div className="table-wrap"><table><thead><tr><th>受管跳</th><th>部署</th><th>观测与检查入口</th></tr></thead><tbody>{current.hop_observations.map(hop => <tr key={hop.server_id}><td>{hop.name}</td><td>{hop.target_revision ?? '—'} / {hop.applied_revision ?? '—'} · {hop.healthy ? '健康' : '待确认'}</td><td>{hop.last_seen ? time(hop.last_seen) : '无连接时间'} · <a href={`#/servers/${hop.server_id}`}>资源与网络检测</a></td></tr>)}</tbody></table></div></>}
      <details><summary>配置与固定运行时历史</summary>{current.history.map(record => <p key={record.revision}>{time(record.created_at)} · 配置 {record.revision} · {record.runtime_version ? `固定版本 ${record.runtime_version}` : '旧部署未保存版本绑定'}{record.artifact_sha256 ? ` · 制品 ${record.artifact_sha256.slice(0, 12)}…` : ''}</p>)}</details>
      <details onToggle={event => { if (event.currentTarget.open) setEditing(true) }}><summary>分批发布、节点迁移与显式备选链路</summary>{editing && <RuntimeWorkflowForms serverId={serverId} onChanged={resource.reload} />}</details>
    </>}
  </section>
}

type Rollout = { id: string; runtime_version: string; targets: number[]; batch_size: number; dispatched_count: number; paused: boolean; created_at: number; completed_at: number | null; members: { server_id: number; confirmed: boolean; checkpoint_confirmed: boolean; state: string; applied_revision: number | null; candidate_artifact_sha256: string }[] }
type RuntimeInventory = { source: string; versions: { version: string; compatible: boolean; reason: string; upstream_release: string; artifacts: { platform: string; sha256: string; bytes: string; signature_verified: boolean; payload_verified: boolean }[] }[] }

function RuntimeWorkflowForms({ serverId, onChanged }: { serverId: number; onChanged: () => void }) {
  const servers = useResource<PluginServer[]>('/api/plugins/sing-box/servers')
  const nodes = useResource<Node[]>('/api/plugins/sing-box/nodes')
  const resources = useResource<ProxyResource[]>('/api/plugins/sing-box/proxy-resources')
  const policies = useResource<PolicyGroup[]>('/api/plugins/sing-box/policy-groups')
  const rollouts = useResource<Rollout[]>('/api/plugins/sing-box/runtime-rollouts')
  const inventory = useResource<RuntimeInventory>('/api/plugins/sing-box/runtime-inventory')
  const action = useAction()
  const [selectedServers, setSelectedServers] = useState<number[]>([serverId])
  const [batchSize, setBatchSize] = useState('5')
  const [runtimeVersion, setRuntimeVersion] = useState('')
  const [source, setSource] = useState('')
  const [candidate, setCandidate] = useState('')
  const [sourceChain, setSourceChain] = useState('')
  const [alternateChain, setAlternateChain] = useState('')
  const [failoverReason, setFailoverReason] = useState('')
  const [selectedGroups, setSelectedGroups] = useState<number[]>([])
  const [operation, setOperation] = useState<WorkflowOperation | null>(null)
  const [notice, setNotice] = useState('')
  const error = resourceWriteError(servers, nodes, resources, policies, rollouts, inventory)
  const selectedVersion = inventory.data?.versions.find(candidate => candidate.version === runtimeVersion)
  const changed = () => { setOperation(null); onChanged(); rollouts.reload(); setNotice('已保存操作，设备确认前保持待应用状态。') }
  const candidates = nodes.data?.filter(node => node.server_id !== serverId) ?? []
  const chains = resources.data?.filter(resource => resource.kind === 'chain') ?? []
  return <div className="panel-body"><ErrorNotice message={servers.error || nodes.error || resources.error || policies.error || rollouts.error || inventory.error || action.error} retry={() => { servers.reload(); nodes.reload(); resources.reload(); policies.reload(); rollouts.reload(); inventory.reload() }} />{notice && <p className="notice notice-success">{notice}</p>}
    <h4>库存版本选择与分批发布</h4><p>从本地已签名且载荷完整的实际库存选择版本。每台目标冻结平台制品摘要，先一台，再按固定批次继续。每个实际发布批次的目标都须先在各自服务器页采集并确认当前五分钟内的完整部署预检。上一批需收到实时运行状态、目标版本与制品健康确认；未知或失败时不能自动继续。</p><Field label="明确选择运行时版本"><select value={runtimeVersion} onChange={event => setRuntimeVersion(event.target.value)}><option value="">选择库存版本</option>{inventory.data?.versions.map(candidate => <option key={candidate.version} value={candidate.version}>{candidate.version} · {candidate.compatible ? '当前编译器兼容' : '兼容门禁未满足'}</option>)}</select></Field>{inventory.data?.versions.length === 0 && <p className="notice">尚无已签名且载荷完整的 sing-box 制品，先导入可信发布。</p>}{selectedVersion && <><p>{selectedVersion.reason} · <a href={selectedVersion.upstream_release} target="_blank" rel="noreferrer">官方版本材料</a></p><div className="table-wrap"><table><thead><tr><th>已验签平台</th><th>真实制品摘要</th><th>归档大小</th></tr></thead><tbody>{selectedVersion.artifacts.map(artifact => <tr key={artifact.platform}><td>{artifact.platform}</td><td><code>{artifact.sha256}</code></td><td>{artifact.bytes} 字节</td></tr>)}</tbody></table></div></>}<div className="group-choices">{servers.data?.map(server => <label className="group-choice" key={server.id}><input type="checkbox" checked={selectedServers.includes(server.id)} disabled={action.busy} onChange={event => setSelectedServers(previous => event.target.checked ? [...previous, server.id] : previous.filter(id => id !== server.id))} /><span>{server.name} · {server.online ? '在线' : '离线'}</span></label>)}</div><p>首台验证：{servers.data?.find(server => server.id === (selectedServers.includes(serverId) ? serverId : selectedServers[0]))?.name ?? '请选择目标'}。</p><Field label="验证首台后的每批台数"><input type="number" min={1} max={20} value={batchSize} onChange={event => setBatchSize(event.target.value)} /></Field><button className="button button-secondary" disabled={action.busy || Boolean(error) || !selectedVersion?.compatible || !selectedServers.length || selectedServers.some(id => !servers.data?.some(server => server.id === id)) || !Number.isInteger(Number(batchSize)) || Number(batchSize) < 1 || Number(batchSize) > 20} onClick={() => void action.run(() => api('/api/plugins/sing-box/runtime-rollouts', 'POST', { server_ids: [...selectedServers], canary_server_id: selectedServers.includes(serverId) ? serverId : selectedServers[0], runtime_version: runtimeVersion, batch_size: Number(batchSize) }), changed)}>确认所选版本和固定目标，先发布一台</button>
    {rollouts.data?.filter(rollout => rollout.targets.includes(serverId)).map(rollout => <div className="notice" key={rollout.id}><div><p>{time(rollout.created_at)} · {rollout.runtime_version} · 已分发 {rollout.dispatched_count}/{rollout.targets.length} · {rollout.completed_at ? `已于 ${time(rollout.completed_at)} 确认全部目标` : rollout.paused ? '暂停' : '等待逐批确认'}</p>{rollout.members.map(member => <p key={member.server_id}>服务器 #{member.server_id} · {member.confirmed ? '设备健康与实际运行时已确认' : member.state === 'failed' ? '操作失败，需读取状态后处理' : '等待设备确认'} · 应用 {member.applied_revision ?? '—'} · 候选制品 {member.candidate_artifact_sha256.slice(0, 12)}… {!member.confirmed && <><button className="text-button" disabled={action.busy || Boolean(error)} onClick={() => void action.run(() => api(`/api/plugins/sing-box/runtime-rollouts/${rollout.id}/members/${member.server_id}/inspect`, 'POST'), changed)}>重新读取状态（不重放部署）</button>{!member.checkpoint_confirmed && <button className="text-button" disabled={action.busy || Boolean(error)} onClick={() => void action.run(() => api(`/api/plugins/sing-box/servers/${member.server_id}/operations-view/checkpoint`, 'POST'), () => { rollouts.reload(); onChanged(); setNotice('已请求核对实际文件、受管进程和签名运行时，等待回执。') })}>核对实际运行时</button>}</>}</p>)}<button className="button button-secondary button-small" disabled={action.busy || Boolean(error) || rollout.paused || rollout.dispatched_count >= rollout.targets.length || rollout.members.some(member => !member.confirmed)} onClick={() => void action.run(() => api(`/api/plugins/sing-box/runtime-rollouts/${rollout.id}/advance`, 'POST'), changed)}>确认继续下一批</button>{' '}<button className="button button-secondary button-small" disabled={action.busy || Boolean(error) || Boolean(rollout.completed_at)} onClick={() => void action.run(() => api(`/api/plugins/sing-box/runtime-rollouts/${rollout.id}/pause`, 'POST', { paused: !rollout.paused }), changed)}>{rollout.paused ? '恢复计划' : '暂停计划'}</button></div></div>)}
    <h4>普通节点迁移助手</h4><p>先在目标服务器克隆独立节点，确认候选服务器的当前目标部署。此处核对入口、协议、授权与订阅关系；历史用量和旧节点保留，Agent 身份不会复制。链路节点使用节点页的候选流程。</p><Field label="当前服务器上的原节点"><select value={source} onChange={event => setSource(event.target.value)}><option value="">选择原节点</option>{nodes.data?.filter(node => node.server_id === serverId).map(node => <option key={node.id} value={node.id}>{node.name}</option>)}</select></Field><Field label="另一服务器的候选节点"><select value={candidate} onChange={event => setCandidate(event.target.value)}><option value="">选择独立候选</option>{candidates.map(node => <option key={node.id} value={node.id}>{node.name} · 服务器 #{node.server_id} · {node.public_host}:{node.port}</option>)}</select></Field><button className="button button-secondary" disabled={action.busy || Boolean(error) || !nodes.data?.some(node => node.id === Number(source) && node.server_id === serverId) || !candidates.some(node => node.id === Number(candidate))} onClick={() => setOperation({ operation: 'migrate_node', source_node_id: Number(source), candidate_node_id: Number(candidate) })}>预览迁移影响</button>
    <h4>显式备选链路切换</h4><p>仅切换选定策略组到已经完成真实路径验证的备选链路。原链路保留，变更有记录；不会绕过链路改为直连。</p><Field label="原链路"><select value={sourceChain} onChange={event => setSourceChain(event.target.value)}><option value="">选择原链路</option>{chains.map(chain => <option key={chain.id} value={chain.id}>{chain.name}</option>)}</select></Field><Field label="明确备选链路"><select value={alternateChain} onChange={event => setAlternateChain(event.target.value)}><option value="">选择已验证备选</option>{chains.filter(chain => String(chain.id) !== sourceChain).map(chain => <option key={chain.id} value={chain.id}>{chain.name}</option>)}</select></Field><div className="group-choices">{policies.data?.filter(policy => policy.chain_ids.includes(Number(sourceChain))).map(policy => <label key={policy.id} className="group-choice"><input type="checkbox" checked={selectedGroups.includes(policy.id)} onChange={event => setSelectedGroups(previous => event.target.checked ? [...previous, policy.id] : previous.filter(id => id !== policy.id))} /><span>{policy.name}</span></label>)}</div><Field label="切换原因"><input value={failoverReason} maxLength={128} onChange={event => setFailoverReason(event.target.value)} placeholder="例如：已确认原链路故障，切换到选定备选" /></Field><button className="button button-secondary" disabled={action.busy || Boolean(error) || !failoverReason.trim() || !sourceChain || !alternateChain || !selectedGroups.length || selectedGroups.some(id => !policies.data?.some(policy => policy.id === id && policy.chain_ids.includes(Number(sourceChain))))} onClick={() => setOperation({ operation: 'failover', source_chain_id: Number(sourceChain), alternate_chain_id: Number(alternateChain), group_ids: [...selectedGroups], reason: failoverReason.trim() })}>预览策略组切换</button>
    {operation && <OperationReview request={operation} onClose={() => setOperation(null)} onApplied={changed} />}
  </div>
}
