import { useState } from 'react'
import { api } from '../../api'
import { Badge, Confirm, Empty, ErrorNotice, Field, Icon, Loading, Modal, PageHeader, Refresh } from '../../components'
import { ddnsMessage, ddnsWrite, providers } from './types'
import type { DdnsConfig, DdnsRule } from './types'
import { resourceWriteError, useAction, useResource } from '../../hooks'
import { ddnsCurrentError, editorError, ruleError, serverError } from './guards'
import type { DdnsCurrent, DdnsServer as Server } from './guards'
import Lifecycle from './Lifecycle'
import Migration from './Migration'
import DnsAccounts from './DnsAccounts'
import './ddns.css'

const time = (value: number) => new Date(value * 1000).toLocaleString('zh-CN', { hour12: false })
const empty: DdnsConfig = { provider: 'cloudflare', line: '', name: '', server_id: 0, zone_id: '', record_name: '', record_type: 'A', ttl: 1, proxied: false, interval_secs: 300, enabled: true, adopt_existing: false }

function Editor({ rule, servers, current, close, saved }: { rule?: DdnsRule; servers: Server[]; current: DdnsCurrent; close: () => void; saved: () => void }) {
  const [config, setConfig] = useState<DdnsConfig>(rule?.config ?? { ...empty, server_id: servers[0]?.id ?? 0 })
  const [addressMode, setAddressMode] = useState<'A' | 'AAAA' | 'dual'>(rule?.config.record_type ?? 'A')
  const [credentialMode, setCredentialMode] = useState(rule?.config.account_id ? 'account' : rule?.config.credential_id ? 'center' : 'legacy')
  const [token, setToken] = useState('')
  const [key, setKey] = useState(''), [secret, setSecret] = useState('')
  const provider = config.provider ?? 'cloudflare', cloudflare = provider === 'cloudflare', namedZone = provider === 'tencent' || provider === 'aliyun'
  const action = useAction()
  const slots = !rule && addressMode === 'dual' ? 2 : 1
  const writeError = () => (addressMode === 'dual' && config.address_source === 'manual' ? '双栈手工地址请分别创建 IPv4 与 IPv6 规则。' : '') || editorError(current, config, rule, slots) || (credentialMode === 'account' ? !config.account_id?.trim() ? '请填写集中 DNS 账号标识。' : '' : credentialMode === 'center' ? !config.credential_id?.trim() ? '请填写凭据中心的 DNS 凭据标识。' : '' : cloudflare ? !rule && !token.trim() ? '请填写 Cloudflare API Token。' : ''
    : Boolean(key.trim()) !== Boolean(secret.trim()) || (!rule && (!key.trim() || !secret.trim())) ? '请同时填写访问密钥 ID 与 Secret。' : '')
  const change = (part: Partial<DdnsConfig>) => setConfig(value => ({ ...value, ...part }))
  return <Modal title={rule ? `编辑动态解析 · ${rule.config.name}` : '添加动态解析'} busy={action.busy} onClose={close} wide className="ddns-editor"><form onSubmit={event => {
    event.preventDefault()
    void action.run(() => { const reason = writeError(); if (reason) throw new Error(reason); return api(rule ? `/api/plugins/ddns/rules/${rule.id}` : addressMode === 'dual' ? '/api/plugins/ddns/rules/dual-stack' : '/api/plugins/ddns/rules', rule ? 'PATCH' : 'POST', ddnsWrite(config, token, rule?.revision, key, secret)) }, () => { setToken(''); setKey(''); setSecret(''); saved() })
  }}><div className="modal-body"><ErrorNotice message={action.error || editorError(current, config, rule, slots)} /><fieldset disabled={action.busy}>
    <div className="ddns-provider"><strong>{providers[provider]}</strong><span>从所选地址来源更新 DNS</span></div>
    <Field label="DNS 提供方"><select value={provider} disabled={Boolean(rule)} onChange={event => { const next = event.target.value as NonNullable<DdnsConfig['provider']>; change({ provider: next, zone_id: '', line: '', proxied: false, ttl: next === 'cloudflare' ? 1 : 600 }); setToken(''); setKey(''); setSecret('') }}>{Object.entries(providers).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Field>
    <div className="form-grid"><Field label="规则名称"><input value={config.name} required maxLength={128} onChange={event => change({ name: event.target.value })} placeholder="例如：家庭服务器 IPv4" /></Field>
      <Field label="绑定服务器"><select value={config.server_id} required onChange={event => change({ server_id: Number(event.target.value) })}>{!servers.some(server => server.id === config.server_id) && <option value={config.server_id}>{rule?.server_name ?? '请选择服务器'}（不可用）</option>}{servers.map(server => <option key={server.id} value={server.id}>{server.name}{!server.online ? '（离线）' : ''}</option>)}</select></Field>
      <Field label="地址来源" hint="网卡地址与公网发现结果分别由 Agent 上报；旧 Agent 缺少所选来源时保留解析。手工来源不依赖服务器在线状态，退役或停用插件仍会阻止同步。"><select value={config.address_source ?? 'agent'} onChange={event => change({ address_source: event.target.value as NonNullable<DdnsConfig['address_source']>, manual_ip: null, interface_name: null })}><option value="agent">Agent 合并地址报告（兼容旧版本）</option><option value="interface">指定网卡地址</option><option value="discovered">Agent 实际发现的公网出口</option><option value="manual">手工公网地址</option></select></Field>
      {config.address_source === 'interface' && <Field label="地址来源网卡" hint="使用此网卡上报的公网单播地址；私有网卡地址不能直接用作 DDNS 公网地址。"><input required value={config.interface_name ?? ''} maxLength={128} list="ddns-address-interfaces" onChange={event => change({ interface_name: event.target.value })} /><datalist id="ddns-address-interfaces">{servers.find(server => server.id === config.server_id)?.interface_names?.map(name => <option key={name} value={name} />)}</datalist></Field>}
      {config.address_source === 'manual' && <Field label="手工公网地址" hint="填写与当前 A / AAAA 类型匹配的公网地址。"><input value={config.manual_ip ?? ''} required maxLength={64} spellCheck={false} onChange={event => change({ manual_ip: event.target.value })} placeholder={config.record_type === 'A' ? 'IPv4 公网地址' : 'IPv6 公网地址'} /></Field>}
      <Field label="完整域名" hint="支持泛域名与中文域名，例如 node.example.com 或 *.example.com。"><input value={config.record_name} disabled={Boolean(rule)} required maxLength={253} autoCapitalize="none" spellCheck={false} onChange={event => change({ record_name: event.target.value })} placeholder="node.example.com" /></Field>
      <Field label="IP 类型" hint="双栈一次创建 A 和 AAAA 两条规则，可分别查看同步状态、编辑或暂停。"><select value={addressMode} disabled={Boolean(rule)} onChange={event => { const mode = event.target.value as typeof addressMode; setAddressMode(mode); change({ record_type: mode === 'AAAA' ? 'AAAA' : 'A' }) }}><option value="A">仅 IPv4</option><option value="AAAA">仅 IPv6</option><option value="dual">IPv4 和 IPv6</option></select></Field>
      <Field label={namedZone ? '托管根域名' : 'Zone ID'} hint={namedZone ? '填写在该云服务托管的根域名，例如 example.com；支持托管子域。' : `在 ${providers[provider]} 复制公网区域的 Zone ID。`}><input value={config.zone_id} disabled={Boolean(rule)} required pattern={namedZone ? undefined : '[a-fA-F0-9]{32}'} maxLength={namedZone ? 253 : 32} spellCheck={false} autoCapitalize="none" onChange={event => change({ zone_id: event.target.value.trim() })} placeholder={namedZone ? 'example.com' : '32 位区域标识'} /></Field>
      {namedZone && <Field label="解析线路标识" hint={provider === 'tencent' ? '默认线路为 0，其他线路填写 DNSPod 的线路 ID。' : '默认线路为 default，其他线路填写阿里云线路代码。'}><input disabled={Boolean(rule)} value={config.line ?? ''} maxLength={64} placeholder={provider === 'tencent' ? '0' : 'default'} onChange={event => change({ line: event.target.value })} /></Field>}
      <Field label="凭据来源"><select value={credentialMode} onChange={event => { const mode = event.target.value; setCredentialMode(mode); change({ credential_id: mode === 'center' ? '' : null, account_id: mode === 'account' ? '' : null }); setToken(''); setKey(''); setSecret('') }}><option value="account">集中 DNS 账号引用</option><option value="center">凭据中心加密引用</option><option value="legacy">当前规则独立凭据</option></select></Field>
      {credentialMode === 'account' && <Field label="集中 DNS 账号标识" hint="复制下方 DNS 账号的标识。账号必须启用并明确授权此提供方、区域和服务器；账号停用、范围变更或凭据轮换会在下次同步重新核对。"><input required maxLength={36} value={config.account_id ?? ''} onChange={event => change({ account_id: event.target.value.trim() })} placeholder="DNS 账号的 UUID" /></Field>}
      {credentialMode === 'center' && <Field label="DNS 凭据标识" hint="在凭据中心创建用途为 DNS 的凭据并复制标识。Cloudflare 使用 api_token；其他提供方使用 access_key_id 与 access_key_secret；可用 provider 指定提供方。"><input value={config.credential_id ?? ''} required maxLength={36} spellCheck={false} pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" onChange={event => change({ credential_id: event.target.value.trim() })} placeholder="DNS 凭据的 UUID" /></Field>}
      {credentialMode === 'legacy' && (cloudflare ? <Field label="API Token" hint={rule ? '已保存的凭据不回显；留空保留，填写则替换。' : '创建仅限此 Zone、包含 DNS 编辑权限的 API 令牌。'}><input type="password" value={token} autoComplete="new-password" required={!rule} minLength={16} maxLength={256} onChange={event => setToken(event.target.value)} placeholder={rule?.token_configured ? '已配置，留空保留' : '输入 Cloudflare API Token'} /></Field> : <><Field label="访问密钥 ID" hint={rule ? '密钥对同时留空保留；替换时同时填写两项。' : '使用仅有目标域名 DNS 权限的子账号密钥。'}><input type="password" autoComplete="new-password" value={key} required={!rule || Boolean(secret)} minLength={8} maxLength={256} onChange={event => setKey(event.target.value)} /></Field><Field label="访问密钥 Secret"><input type="password" autoComplete="new-password" value={secret} required={!rule || Boolean(key)} minLength={8} maxLength={256} onChange={event => setSecret(event.target.value)} /></Field></>)}
      <Field label="TTL（秒）" hint={cloudflare ? '1 表示自动；手动范围为 60–86400 秒。' : '60–86400 秒；还需满足所购域名套餐的最小 TTL，建议从 600 秒开始。'}><input type="number" required min={cloudflare ? 1 : 60} max={86400} step={1} value={config.proxied ? 1 : config.ttl} disabled={config.proxied} onChange={event => change({ ttl: Number(event.target.value) })} /></Field>
      <Field label="检查间隔（秒）" hint="60–86400 秒；仅在地址或设置变化时更新 DNS。"><input type="number" required min={60} max={86400} step={1} value={config.interval_secs} onChange={event => change({ interval_secs: Number(event.target.value) })} /></Field>
    </div>
    {cloudflare && <label className="ddns-toggle"><input type="checkbox" checked={config.proxied} onChange={event => change({ proxied: event.target.checked })} /><span><strong>启用 Cloudflare 代理</strong><small>代理仅适用于 Cloudflare 支持的流量与端口，会自动使用自动 TTL；普通代理协议通常应保持关闭。</small></span></label>}
    <label className="ddns-toggle"><input type="checkbox" checked={config.adopt_existing} onChange={event => change({ adopt_existing: event.target.checked })} /><span><strong>接管已有的同名同类型记录</strong><small>勾选后允许覆盖指定线路唯一已有记录的 IP、TTL 和代理设置。重复或多值记录请先在提供方整理。</small></span></label>
    <label className="ddns-toggle"><input type="checkbox" checked={config.enabled} onChange={event => change({ enabled: event.target.checked })} /><span><strong>启用自动同步</strong><small>保存后按间隔同步；Agent 来源离线、无有效公网地址时保留现有解析。手工地址不依赖在线状态。暂停或删除规则不会删除 DNS 记录。</small></span></label>
    {rule && (rule.config.server_id !== config.server_id || (rule.config.address_source ?? 'agent') !== (config.address_source ?? 'agent') || rule.config.manual_ip !== config.manual_ip) && <p className="helper">保存后的影响：地址来源从“{rule.server_name} · {rule.config.address_source === 'manual' ? rule.config.manual_ip : 'Agent 报告'}”变更为“{servers.find(server => server.id === config.server_id)?.name ?? config.server_id} · {config.address_source === 'manual' ? config.manual_ip || '待填写' : 'Agent 报告'}”。下轮同步按新来源更新此域名，服务器 Agent 身份不复制。</p>}
    <p className="helper">多地址优先沿用仍在 Agent 报告中的上次成功地址，否则按地址排序选取首个。若服务器处于 NAT 后，请在采样设置中启用公网 IP 发现。{rule && '提供方、区域、域名、类型和线路固定，变更时请另建规则。'}</p>
  </fieldset></div><footer><button type="button" className="button button-secondary" disabled={action.busy} onClick={close}>取消</button><button className="button button-primary" disabled={action.busy || Boolean(writeError())}>{action.busy ? '正在保存…' : '保存规则'}</button></footer></form></Modal>
}

export default function Ddns({ serverId }: { serverId?: number }) {
  const [migrating, setMigrating] = useState(false)
  const [lifecycle, setLifecycle] = useState<DdnsRule | null>(null)
  const [editing, setEditing] = useState<DdnsRule | 'new' | null>(null), [removing, setRemoving] = useState<DdnsRule | null>(null)
  const rules = useResource<DdnsRule[]>('/api/plugins/ddns/rules'), servers = useResource<Server[]>('/api/plugins/ddns/servers')
  const action = useAction()
  const available = Boolean(rules.data && servers.data && !resourceWriteError(rules, servers))
  const scope = servers.data?.filter(server => !serverId || server.id === serverId) ?? []
  const enabledServers = scope.filter(server => server.enabled)
  const visibleRules = rules.data?.filter(rule => !serverId || rule.config.server_id === serverId)
  const refresh = () => { rules.reload(); servers.reload() }
  const current: DdnsCurrent = () => {
    if (resourceWriteError(rules, servers)) return undefined
    return { rules: rules.getCurrent()!, servers: servers.getCurrent()!.filter(server => !serverId || server.id === serverId) }
  }
  const perform = (error: () => string, request: () => Promise<unknown>, saved = rules.reload) => void action.run(() => { const reason = error(); if (reason) throw new Error(reason); return request() }, saved)
  const open = (rule: DdnsRule | 'new') => { if (rule === 'new' ? ddnsCurrentError(current) : ruleError(current, rule)) return; action.clearError(); setEditing(rule) }
  return <div className="ddns-page"><PageHeader eyebrow="服务器网络" title="动态域名解析" description="让域名跟随服务器公网 IP 更新，支持 Cloudflare、腾讯云、阿里云和华为云。"><Refresh onClick={refresh} /><button className="button button-secondary" disabled={action.busy || !available || !enabledServers.length || !visibleRules?.length} onClick={() => setMigrating(true)}>批量迁移与编辑</button><button className="button button-primary" disabled={action.busy || !available || !enabledServers.length || (rules.data?.length ?? 32) >= 32} onClick={() => open('new')}><Icon name="plus" size={16} />添加规则</button></PageHeader>
    <ErrorNotice message={rules.error || servers.error || action.error} retry={refresh} />
    {servers.data && <DnsAccounts servers={servers.data} />}
    <section className="panel"><div className="panel-heading"><h2>DDNS 插件启用状态</h2><Badge>面板插件</Badge></div><div className="panel-body"><p className="helper">按服务器启用；使用已有 Agent 上报的 IP，云服务凭据与 DNS 更新由面板插件管理。无需在设备上下载或安装额外程序。</p>{scope.map(server => <div className="ddns-rule-footer ddns-activation" key={server.id}><span>{server.name} · {server.enabled ? '插件已启用' : '插件未启用'}</span><button className="button button-secondary button-small" disabled={action.busy || !available} onClick={() => perform(() => serverError(current, server), () => api(`/api/plugins/ddns/servers/${server.id}/${server.enabled ? 'disable' : 'enable'}`, 'POST'), refresh)}>{server.enabled ? '停用 DDNS 插件' : '启用 DDNS 插件'}</button></div>)}{!scope.length && <p className="helper">{servers.error || !servers.data ? '服务器状态暂不可用。' : serverId ? '指定服务器不存在或不可用。' : '请先添加服务器，再启用 DDNS 插件。'}</p>}</div></section>
    <section className="panel"><div className="panel-heading"><h2>域名解析规则</h2><span className="subtle">{rules.error || !rules.data ? '—' : rules.data.length} / 32 条</span></div>
      {!rules.data && rules.loading ? <Loading /> : !rules.data || (rules.error && !visibleRules?.length) ? <Empty icon="nodes" title="规则状态暂不可用" description="请刷新读取规则和服务器状态后再操作。" /> : !visibleRules?.length ? <Empty icon="nodes" title="尚未配置动态解析" description="选择提供方并配置域名、区域和云服务凭据，绑定已经接入 Agent 的服务器。" /> : <div className="ddns-list">{visibleRules.map(rule => <article className="ddns-rule" key={rule.id}>
        <div className="ddns-rule-heading"><div><h3>{rule.config.name}</h3><code>{rule.config.record_name}</code><span className="subtle"> · {rule.config.record_type}</span></div><Badge tone={!available || !rule.config.enabled || !rule.plugin_enabled ? 'neutral' : rule.error_code || rule.ip_status !== 'ready' ? 'warm' : rule.last_success_at !== null ? 'good' : 'neutral'}>{!available ? '状态未知' : !rule.plugin_enabled ? '插件未启用' : !rule.config.enabled ? '已暂停' : rule.busy ? '正在同步' : rule.ip_status !== 'ready' ? ddnsMessage(rule.ip_status) : ddnsMessage(rule.status === 'running' ? 'pending' : rule.status)}</Badge></div>
        <dl className="ddns-details"><div><dt>绑定服务器</dt><dd>{rule.server_name}</dd></div><div><dt>本次候选地址</dt><dd className="mono">{!available ? '当前状态未知' : rule.candidate_ip ?? '等待有效地址'}</dd></div><div><dt>上次成功地址</dt><dd className="mono">{rule.last_ip ?? '尚未同步'}</dd></div><div><dt>检查间隔 / TTL</dt><dd>{rule.config.interval_secs} 秒 / {rule.config.ttl === 1 ? '自动' : `${rule.config.ttl} 秒`}</dd></div><div><dt>最近成功核对</dt><dd>{rule.last_success_at !== null ? time(rule.last_success_at) : '尚未成功'}</dd></div><div><dt>下次检查</dt><dd>{!available ? '当前状态未知' : !rule.config.enabled || !rule.plugin_enabled ? '暂停期间不检查' : rule.busy ? '正在检查' : rule.next_run_at ? time(rule.next_run_at) : '即将检查'}</dd></div></dl>
        <div className="ddns-rule-footer"><span className="subtle">{providers[rule.config.provider ?? 'cloudflare']} · {rule.config.line || '默认线路'} · {rule.config.proxied ? '已开启 Cloudflare 代理' : '仅 DNS'} · {rule.config.account_id ? '集中 DNS 账号' : rule.config.credential_id ? '凭据中心引用' : '独立凭据'}{rule.token_configured ? '已配置' : '未配置'}{rule.ip_received_at !== null && ` · IP 报告 ${time(rule.ip_received_at)}`}</span><div className="ddns-actions"><button className="text-button" disabled={action.busy || !available || rule.busy || !rule.config.enabled || !rule.plugin_enabled} onClick={() => perform(() => ruleError(current, rule, true), () => api(`/api/plugins/ddns/rules/${rule.id}/sync`, 'POST'))}>立即同步</button><button className="text-button" disabled={action.busy || !available || rule.busy} onClick={() => setLifecycle(rule)}>核对与历史</button><button className="text-button" disabled={action.busy || !available || rule.busy} onClick={() => open(rule)}>编辑</button><button className="text-button" disabled={action.busy || !available || rule.busy || (!rule.config.enabled && !rule.plugin_enabled)} onClick={() => perform(() => ruleError(current, rule) || (!rule.config.enabled && !current()?.servers.find(server => server.id === rule.config.server_id)?.enabled ? '请先启用此服务器的 DDNS 插件。' : ''), () => api(`/api/plugins/ddns/rules/${rule.id}`, 'PATCH', ddnsWrite({ ...rule.config, enabled: !rule.config.enabled }, '', rule.revision)))}>{rule.config.enabled ? '暂停' : '启用'}</button><button className="text-button danger-text" disabled={action.busy || !available || rule.busy} onClick={() => { action.clearError(); setRemoving(rule) }}>删除</button></div></div>
        {(rule.error_code || rule.ip_status !== 'ready') && <p className="ddns-status" role="status">{ddnsMessage(rule.error_code) || ddnsMessage(rule.ip_status)}</p>}
      </article>)}</div>}
    </section><p className="helper">同步状态区分已提交和已核对；提供方已接收不代表各地解析已生效；各地 DNS 缓存生效仍受 TTL 影响。手动同步有 60 秒冷却，限流或失败时等待页面显示的重试时间。</p>
    {migrating && rules.data && servers.data && <Migration rules={visibleRules ?? []} servers={servers.data} close={() => setMigrating(false)} saved={() => { setMigrating(false); refresh() }} />}
    {lifecycle && <Lifecycle rule={rules.data?.find(rule => rule.id === lifecycle.id) ?? lifecycle} close={() => setLifecycle(null)} changed={refresh} />}
    {editing && servers.data && <Editor key={editing === 'new' ? 'new' : editing.id} rule={editing === 'new' ? undefined : editing} servers={enabledServers} current={current} close={() => setEditing(null)} saved={() => { setEditing(null); refresh() }} />}
    {removing && <Confirm title="删除动态解析规则" busy={action.busy} error={action.error} confirmDisabled={Boolean(ruleError(current, removing))} onClose={() => setRemoving(null)} onConfirm={() => perform(() => ruleError(current, removing), () => api(`/api/plugins/ddns/rules/${removing.id}`, 'DELETE'), () => { setRemoving(null); rules.reload() })}>确认删除“{removing.config.name}”？云服务中的 DNS 记录会保留，之后不再自动更新。</Confirm>}
  </div>
}
