import { useEffect, useState } from 'react'
import { api } from '../api'
import type { Server } from '../types'
import type { ActionRunner, Incident } from './types'
import { states, time } from './types'

type Detail = { incident: Incident; timeline: { id: number; kind: string; note: string; created_at: number; evidence: unknown }[]; deliveries: { id: number; channel: string; status: string; attempts: number; last_error: string | null }[] }
const kinds: Record<string, string> = { opened: '故障发生', acknowledge: '人工确认', assign: '分派处理', note: '处理备注', resolve: '人工恢复核对', recovery_observed: '新观测确认恢复', escalated: '升级提醒', escalation: '调整升级间隔' }

export default function IncidentsTab({ servers, run, version }: { servers: Server[]; run: ActionRunner; version: number }) {
  const [incidents, setIncidents] = useState<Incident[]>([])
  const [detail, setDetail] = useState<Detail | null>(null)
  const [note, setNote] = useState('')
  const [assignee, setAssignee] = useState('')
  const [assignees, setAssignees] = useState<{ id: number; name: string }[]>([])
  const [method, setMethod] = useState('')
  const [reference, setReference] = useState('')
  const [observedAt, setObservedAt] = useState('')
  const [escalation, setEscalation] = useState(3600)
  const refresh = async () => setIncidents(await api<Incident[]>('/api/operations/incidents'))
  useEffect(() => { run(refresh) }, [version]) // eslint-disable-line react-hooks/exhaustive-deps
  const load = async (id: string) => {setDetail(await api<Detail>(`/api/operations/incidents/${id}`));setAssignees(await api<{id:number;name:string}[]>(`/api/operations/incidents/${id}/assignees`).catch(()=>[]))}
  const action = async (kind: string, extra: Record<string, unknown> = {}) => { if (!detail) return; await api(`/api/operations/incidents/${detail.incident.id}/action`, 'POST', { kind, note, assignee: null, evidence: null, escalation_after_secs: null, ...extra }); setNote(''); await load(detail.incident.id); await refresh() }
  return <div className="operations-stack"><section className="operations-card"><h3>故障事件</h3><p>同一来源的故障聚合展示，保留原始告警、服务与任务证据。没有新数据时保持待处理。</p><div className="operations-table-wrap"><table><thead><tr><th>事件</th><th>范围</th><th>状态</th><th>发生／观测</th><th>处理</th></tr></thead><tbody>{incidents.map(incident => <tr key={incident.id}><td>{incident.title}<small>{incident.severity === 'critical' ? '严重' : incident.severity === 'warning' ? '警告' : '提示'}</small></td><td>{servers.find(server => server.id === incident.server_id)?.name ?? (incident.server_id ? `服务器 ${incident.server_id}` : '面板')}<small>{incident.maintenance_suppressed ? '维护期间抑制通知' : ''}</small></td><td>{states[incident.status]}{incident.escalated_at && <small>已升级提醒</small>}</td><td>{time(incident.opened_at)}<small>最近证据 {time(incident.observed_at)}</small></td><td><button onClick={() => run(() => load(incident.id))}>查看证据与处理</button></td></tr>)}</tbody></table></div>{!incidents.length && <p>暂无故障事件。</p>}</section>
    {detail && <section className="operations-card"><h3>{detail.incident.title}</h3><p>{states[detail.incident.status]} · 持续 {(Math.max(0, (detail.incident.resolved_at ?? Math.floor(Date.now() / 1000)) - detail.incident.opened_at) / 60).toFixed(1)} 分钟</p><details><summary>检测来源与原始证据</summary><pre>{JSON.stringify(detail.incident.evidence, null, 2)}</pre></details>{detail.incident.recovery_evidence != null && <details><summary>恢复依据</summary><pre>{JSON.stringify(detail.incident.recovery_evidence, null, 2)}</pre></details>}<label>处理备注／人工结论<textarea value={note} onChange={event => setNote(event.target.value)} maxLength={4096} /></label><div className="operations-actions"><button disabled={!note.trim() || detail.incident.status === 'resolved'} onClick={() => run(() => action('acknowledge'))}>确认正在处理</button><button disabled={!note.trim()} onClick={() => run(() => action('note'))}>添加备注</button><label>处理管理员<select value={assignee} onChange={event => setAssignee(event.target.value)}><option value="">选择有权限的处理人</option>{assignees.map(admin => <option key={admin.id} value={admin.id}>{admin.name}</option>)}</select></label><button disabled={!note.trim() || !assignee} onClick={() => run(() => action('assign', { assignee: Number(assignee) }))}>分派</button></div><label>未恢复后的升级间隔（秒）<input type="number" min={60} max={604800} value={escalation} onChange={event => setEscalation(Number(event.target.value))} /></label><button disabled={!note.trim()} onClick={() => run(() => action('escalation', { escalation_after_secs: escalation }))}>保存升级提醒规则</button>
      {detail.incident.status !== 'resolved' && <fieldset><legend>恢复核对</legend><p>提供故障发生后、最近十分钟内的实际正常结果，以及可核对的来源。</p><div className="operations-fields"><label>检查方法<input value={method} onChange={event => setMethod(event.target.value)} placeholder="例如：从指定服务器探测服务并得到预期响应" /></label><label>证据引用<input value={reference} onChange={event => setReference(event.target.value)} placeholder="实际报告、任务或日志引用" /></label><label>观测时间<input type="datetime-local" value={observedAt} onChange={event => setObservedAt(event.target.value)} /></label></div><button disabled={!note.trim() || !method.trim() || !reference.trim() || !observedAt} onClick={() => run(() => action('resolve', { evidence: { observed_at: Math.floor(new Date(observedAt).getTime() / 1000), method, reference, healthy: true } }))}>确认该观测正常并记录恢复</button></fieldset>}
      <h4>故障时间线</h4>{detail.timeline.map(entry => <article key={entry.id}><strong>{time(entry.created_at)} · {kinds[entry.kind] ?? '处理记录'}</strong><p>{entry.note}</p><details><summary>关联证据</summary><pre>{JSON.stringify(entry.evidence, null, 2)}</pre></details></article>)}<h4>通知结果</h4>{detail.deliveries.map(delivery => <p key={delivery.id}>{delivery.channel === 'telegram' ? 'Telegram' : 'Webhook'} · {delivery.status === 'sent' ? '已投递' : delivery.status === 'pending' ? '等待投递' : delivery.status === 'cancelled' ? '已取消' : '投递失败'} · {delivery.attempts} 次尝试 {delivery.last_error}</p>)}<button onClick={() => { const blob = new Blob([JSON.stringify(detail, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `incident-${detail.incident.id}.json`; anchor.click(); URL.revokeObjectURL(url) }}>导出含证据的故障报告</button>
    </section>}</div>
}
