import { useEffect, useState } from 'react'
import { api } from '../api'
import type { Server } from '../types'
import type { ActionRunner, BackupScheduleOption, Job, JobDetail, Maintenance, Plan, Preview, Schedule, Step, Template } from './types'
import { states, time } from './types'
import RemediationRules from './RemediationRules'
import CancellationReminders from './CancellationReminders'
import FleetReconciliation from './FleetReconciliation'
import FormDraftToolbar from '../control-center/FormDraftToolbar'

const defaults: Plan = { name: '服务器检查', steps: [{ kind: 'system_snapshot', service: null, timeout_secs: 300 }], batch_size: 4, concurrency: 2, pause_between_batches: true, max_duration_secs: 3600 }
const stepNames: Record<Step['kind'], string> = { system_snapshot: '系统只读快照', service_status: '服务状态', service_start: '启动服务', service_stop: '停止服务', service_restart: '重启服务', singbox_retry_deployment: '重新应用已有失败的签名部署', panel_backup: '完整面板恢复点（整项任务一次）' }
const actionNames: Record<string, string> = { preview: '执行预览', confirmed: '确认执行', scheduled: '计划触发', started: '开始执行', batch_paused: '批次待确认', batch_resumed: '确认继续批次', cancel_requested: '请求取消', execution_queued: '设备操作排队', finished: '执行结束', uncertain: '执行结果未知', reconciled: '人工核对停止', remediation_triggered: '自动处置触发' }

type Actor = { role: string; all_servers: boolean; capabilities: string[]; token_capabilities?: string[] | null; token_servers?: number[] | null }
const allows = (actor: Actor | null, capability: string) => Boolean(actor && (actor.role === 'owner' || actor.capabilities.includes(capability)) && (actor.role !== 'viewer' || !capability.endsWith(':write')) && (!actor.token_capabilities || actor.token_capabilities.includes(capability)))
const globalServers = (actor: Actor | null) => Boolean(actor?.all_servers && !actor.token_servers)
const isService = (step: Step) => step.kind.startsWith('service_')
const canChoose = (actor: Actor | null, kind: Step['kind']) => allows(actor, 'operations:write') && (kind === 'panel_backup' ? globalServers(actor) && allows(actor, 'recovery:read') && allows(actor, 'recovery:write') : kind === 'singbox_retry_deployment' ? allows(actor, 'proxy:read') && allows(actor, 'proxy:write') : kind === 'service_status' ? allows(actor, 'services:read') : kind.startsWith('service_') ? allows(actor, 'services:write') : allows(actor, 'operations:read'))

function StepEditor({ step, index, choices, backups, update }: { step: Step; index: number; choices: Step['kind'][]; backups: BackupScheduleOption[]; update: (step: Step) => void }) {
  const panel = step.kind === 'panel_backup'
  const runtime = step.kind === 'singbox_retry_deployment'
  const changeKind = (kind: Step['kind']) => update({ kind, service: kind.startsWith('service_') ? step.service ?? '' : null, timeout_secs: kind === 'panel_backup' ? 900 : Math.max(1, Math.min(600, step.timeout_secs)), runtime_version: kind === 'singbox_retry_deployment' ? '1.14.2' : null, backup_schedule_id: kind === 'panel_backup' ? '' : null })
  return <><select aria-label={`步骤 ${index + 1} 类型`} value={step.kind} onChange={event => changeKind(event.target.value as Step['kind'])}>{!choices.includes(step.kind) && <option value={step.kind} disabled>{stepNames[step.kind]}（权限或顺序不可用）</option>}{choices.map(kind => <option key={kind} value={kind}>{stepNames[kind]}</option>)}</select>
    {isService(step) && <input aria-label="已授权服务名" placeholder="已授权服务名" value={step.service ?? ''} onChange={event => update({ ...step, service: event.target.value })} />}
    {runtime && <span>固定可信版本 1.14.2；仅重新应用设备已回报失败的当前部署，不生成新业务配置。需要在线 Agent、制品验签、运行时运维和实际配置核对能力。</span>}
    {panel && <label>已登记的加密备份计划<select value={step.backup_schedule_id ?? ''} onChange={event => update({ ...step, backup_schedule_id: event.target.value })}><option value="">明确选择备份设置</option>{step.backup_schedule_id && !backups.some(backup => backup.id === step.backup_schedule_id) && <option value={step.backup_schedule_id} disabled>当前引用不可读或已失效：{step.backup_schedule_id}</option>}{backups.map(backup => <option key={backup.id} value={backup.id}>{backup.name}{backup.paused ? '（定时已暂停，仍可明确创建本次恢复点）' : ''}</option>)}</select><small>只允许作为第一步，整项任务执行一次；需要所有服务器范围的恢复读写授权。先在“备份恢复”登记加密接收方和保留设置。</small></label>}
    <label>{panel ? '执行预算（秒）' : runtime ? '完成与核对预算（秒）' : '领取期限（秒）'}<input type="number" min={panel ? 60 : 1} max={panel ? 1800 : 600} value={step.timeout_secs} onChange={event => update({ ...step, timeout_secs: Number(event.target.value) })} /></label>
  </>
}

function TypedPreview({ preview, servers }: { preview: Preview; servers: Server[] }) {
  return <>{preview.spec.typed_steps?.map(step => <article key={step.position}><h4>步骤 {step.position + 1} · {stepNames[step.kind]}</h4>{step.backup && <p>{step.backup.name} · 首步仅执行一次，所有目标共同等待实际完整恢复点。固定设置摘要：{step.backup_digest}</p>}{step.targets && Object.entries(step.targets).map(([id, candidate]) => <p key={id}>{servers.find(server => String(server.id) === id)?.name ?? `服务器 ${id}`} · 目标版本 {candidate.binding.revision} · 运行时 {candidate.runtime_version} · 平台 {candidate.artifact.arch}<br />配置包：{candidate.binding.bundle_sha256}<br />签名制品：{candidate.artifact.sha256} · 来源 {candidate.artifact.source_repo} / {candidate.artifact.release_tag}</p>)}<details><summary>完整固定候选与执行器参数</summary><pre>{JSON.stringify(step, null, 2)}</pre></details></article>)}</>
}

type RuntimeReadResponse = { server_id: number; checkpoint_request_id: string; expires_at: number }
type RuntimeReadStatus = { request_id: string; state: string; outcome: string | null; received_at: number | null; result: unknown }
type RuntimeRead = RuntimeReadResponse & { evidence: string; status?: RuntimeReadStatus }
type OperationDraft = { plan: Plan; targets: number[]; template_id: string | null }

function TypedResults({ detail, actor, run, refresh }: { detail: JobDetail; actor: Actor | null; run: ActionRunner; refresh: () => Promise<void> }) {
  const [reads, setReads] = useState<Record<number, RuntimeRead>>({})
  const [panelForm, setPanelForm] = useState(false)
  const [stopped, setStopped] = useState(false)
  const [cleaned, setCleaned] = useState(false)
  const [observedAt, setObservedAt] = useState('')
  const [evidence, setEvidence] = useState('')
  useEffect(() => { setReads({}); setPanelForm(false); setStopped(false); setCleaned(false); setObservedAt(''); setEvidence('') }, [detail.job.id])
  const canReconcileRuntime = allows(actor, 'operations:write') && allows(actor, 'proxy:read') && allows(actor, 'proxy:write')
  const canReconcilePanel = allows(actor, 'operations:write') && globalServers(actor) && allows(actor, 'recovery:write')
  const unknownServers = [...new Set(detail.steps.filter(step => step.runtime_operation_id && step.state === 'uncertain').map(step => step.server_id))]
  const readStatus = async (server: number, request: string) => {
    const actual = await api<{ requests: RuntimeReadStatus[] }>(`/api/servers/${server}/runtime-control`)
    setReads(previous => previous[server]?.checkpoint_request_id === request ? { ...previous, [server]: { ...previous[server], status: actual.requests.find(value => value.request_id === request) } } : previous)
    await refresh()
  }
  return <>
    {detail.panel_steps?.map(step => <article className="operations-review" key={step.execution_id}><h4>完整面板恢复点 · 整项任务一次 · {states[step.state] ?? step.state}</h4><p>执行编号：{step.execution_id}<br />实际恢复点：{step.backup_id ?? '尚无确认成功的恢复点'}<br />开始 {time(step.claimed_at)} · 结束 {time(step.finished_at)}</p><details><summary>一次备份的实际执行回执</summary><pre>{JSON.stringify(step.result, null, 2)}</pre></details>{step.state === 'uncertain' && <><p>面板备份执行或临时材料清理尚未确认。人工核对保留原未知结果，后续步骤停止。</p>{canReconcilePanel && <button onClick={() => setPanelForm(true)}>记录实际停止与清理</button>}</>}</article>)}
    {panelForm && <div className="operations-review"><h4>核对本次面板备份执行</h4><label><input type="checkbox" checked={stopped} onChange={event => setStopped(event.target.checked)} />已实际确认本次备份进程停止</label><label><input type="checkbox" checked={cleaned} onChange={event => setCleaned(event.target.checked)} />已实际检查并清理本次临时材料</label><label>实际观察时间<input type="datetime-local" value={observedAt} onChange={event => setObservedAt(event.target.value)} /></label><label>检查方法、来源和实际结果<textarea value={evidence} maxLength={4096} onChange={event => setEvidence(event.target.value)} /></label><p>此记录不会把备份标为成功。只有检查本次执行的精确进程与私有暂存材料后才提交。</p><button disabled={!canReconcilePanel || !stopped || !cleaned || !observedAt || !evidence.trim()} onClick={() => run(async () => { await api(`/api/operations/jobs/${detail.job.id}/panel-backup/reconcile`, 'POST', { process_stopped: true, temporary_material_cleaned: true, observed_at: Math.floor(new Date(observedAt).getTime() / 1000), evidence }); setPanelForm(false); await refresh() }, true)}>验证身份并记录核对，停止后续步骤</button></div>}
    {unknownServers.map(server => { const read = reads[server]; const verified = read?.status?.outcome === 'verified' && read.status.received_at !== null && Math.floor(Date.now() / 1000) - read.status.received_at >= 0 && Math.floor(Date.now() / 1000) - read.status.received_at < 300; return <article className="operations-review" key={server}><h4>服务器 {server} · 部署结果未知</h4><p>保留原请求和实际结果。先重新读取签名实例与精确配置，再由管理员核对；原部署不会重新提交，人工核对后停止后续步骤。</p>{canReconcileRuntime ? <><button onClick={() => run(async () => { const next = await api<RuntimeReadResponse>(`/api/operations/jobs/${detail.job.id}/runtime-reconcile/checkpoint`, 'POST', { server_id: server }); setReads(previous => ({ ...previous, [server]: { ...next, server_id: server, evidence: previous[server]?.evidence ?? '' } })); await refresh() }, true)}>{read ? '重新发起只读配置核对' : '验证身份并获取新的实际配置核对'}</button>{read && <><p>只读请求：{read.checkpoint_request_id} · 执行窗口至 {time(read.expires_at)} · {verified ? '已收到新鲜 verified 回执' : '等待实际核对回执'}</p><button onClick={() => run(() => readStatus(server, read.checkpoint_request_id))}>读取实际核对回执</button><details><summary>查看只读核对原始结果</summary><pre>{JSON.stringify(read.status ?? { state: 'pending' }, null, 2)}</pre></details><label>根据实际回执填写核对结论<input value={read.evidence} maxLength={4096} placeholder="填写实际回执的简短核对结论" onChange={event => setReads(previous => ({ ...previous, [server]: { ...previous[server], evidence: event.target.value } }))} /></label><button disabled={!verified || !read.evidence.trim()} onClick={() => run(async () => { await api(`/api/operations/jobs/${detail.job.id}/runtime-reconcile`, 'POST', { server_id: server, checkpoint_request_id: read.checkpoint_request_id, evidence: read.evidence }); await refresh() }, true)}>验证身份并核对原部署，停止后续步骤</button><p>服务端仍须确认本次回执与原固定部署、制品、当前实例匹配。失败、过期或不同部署的回执不能解锁。</p></>}</> : <p>此流程需要当前服务器的运维读写及代理业务读写授权。</p>}</article> })}
  </>
}

export default function JobsTab({ servers, selectedServerId, allowTargetSelection = true, run, version }: { servers: Server[]; selectedServerId?: number; allowTargetSelection?: boolean; run: ActionRunner; version: number }) {
  const [plan, setPlan] = useState<Plan>(defaults)
  const [actor, setActor] = useState<Actor | null>(null)
  const [backupSchedules, setBackupSchedules] = useState<BackupScheduleOption[]>([])
  const [targets, setTargets] = useState<number[]>(selectedServerId && allowTargetSelection ? [selectedServerId] : [])
  const [jobs, setJobs] = useState<Job[]>([])
  const [templates, setTemplates] = useState<Template[]>([])
  const [templateId, setTemplateId] = useState<string | null>(null)
  const [preview, setPreview] = useState<Preview | null>(null)
  const [detail, setDetail] = useState<JobDetail | null>(null)
  const [schedules, setSchedules] = useState<Schedule[]>([])
  const [maintenance, setMaintenance] = useState<Maintenance[]>([])
  const [scheduleAt, setScheduleAt] = useState('')
  const [interval, setInterval] = useState(86400)
  const [missed, setMissed] = useState('skip')
  const [maxRuns, setMaxRuns] = useState(30)
  const [maintenanceStart, setMaintenanceStart] = useState('')
  const [maintenanceEnd, setMaintenanceEnd] = useState('')
  const [blockTasks, setBlockTasks] = useState(true)
  const [suppress, setSuppress] = useState(true)
  const [reconciliation, setReconciliation] = useState<{ server: number; operation: string } | null>(null)
  const [draftBaseline, setDraftBaseline] = useState(() => JSON.stringify({ plan: defaults, targets: selectedServerId && allowTargetSelection ? [selectedServerId] : [], template_id: null }))
  const [draftIssue, setDraftIssue] = useState('')

  useEffect(() => { run(async () => { const currentActor = await api<Actor>('/api/control-center/me'); setActor(currentActor); const [nextJobs, nextTemplates, nextSchedules, nextMaintenance, nextBackups] = await Promise.all([api<Job[]>('/api/operations/jobs'), api<Template[]>('/api/operations/templates'), api<Schedule[]>('/api/operations/schedules'), api<Maintenance[]>('/api/operations/maintenance'), globalServers(currentActor) && allows(currentActor, 'recovery:read') ? api<BackupScheduleOption[]>('/api/operations/backup-schedules') : Promise.resolve<BackupScheduleOption[]>([])]); setJobs(nextJobs); setTemplates(nextTemplates); setSchedules(nextSchedules); setMaintenance(nextMaintenance); setBackupSchedules(nextBackups) }) }, [version]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (selectedServerId && allowTargetSelection) setTargets([selectedServerId]); else if (!allowTargetSelection) setTargets([]) }, [selectedServerId, allowTargetSelection])
  useEffect(() => { setReconciliation(null) }, [detail?.job.id])
  const change = (next: Plan) => { setPlan(next); setPreview(null); setTemplateId(null); setDraftIssue('') }
  const draft: OperationDraft = { plan, targets, template_id: templateId }
  const restoreDraft = (value: OperationDraft) => {
    const restored = value?.plan
    if (!restored || typeof restored.name !== 'string' || !Array.isArray(restored.steps) || !restored.steps.length || restored.steps.length > 16 || restored.steps.some(step => !step || !Object.hasOwn(stepNames, step.kind) || (step.service !== null && typeof step.service !== 'string') || !Number.isFinite(step.timeout_secs)) || ![restored.batch_size, restored.concurrency, restored.max_duration_secs].every(Number.isFinite) || typeof restored.pause_between_batches !== 'boolean' || !Array.isArray(value.targets) || value.targets.some(id => !Number.isInteger(id) || !servers.some(server => server.id === id)) || (!allowTargetSelection && value.targets.length)) { setDraftIssue('保存的草稿格式或服务器范围已不适用，当前输入已保留。请核对权限及目标范围。'); return }
    const next: OperationDraft = { plan: { name: restored.name, batch_size: restored.batch_size, concurrency: restored.concurrency, max_duration_secs: restored.max_duration_secs, pause_between_batches: restored.pause_between_batches, steps: restored.steps.map(step => ({ kind: step.kind, service: isService(step) ? step.service : null, timeout_secs: step.timeout_secs, runtime_version: step.kind === 'singbox_retry_deployment' ? step.runtime_version ?? '1.14.2' : null, backup_schedule_id: step.kind === 'panel_backup' ? step.backup_schedule_id ?? null : null })) }, targets: [...new Set(value.targets)], template_id: typeof value.template_id === 'string' ? value.template_id : null }
    setPlan(next.plan); setTargets(next.targets); setTemplateId(next.template_id); setPreview(null); setDraftIssue(''); setDraftBaseline(JSON.stringify(next))
  }
  const loadDetail = async (id: string) => setDetail(await api<JobDetail>(`/api/operations/jobs/${id}`))
  const updateStep = (index: number, next: Step) => change({ ...plan, steps: plan.steps.map((step, position) => position === index ? next : step) })
  const toggle = (id: number) => { setTargets(previous => previous.includes(id) ? previous.filter(value => value !== id) : [...previous, id]); setPreview(null) }
  const currentZoneOffset = -new Date().getTimezoneOffset()
  const runtimeCapabilities = ['runtime:operations:v1', 'runtime:checkpoint-v1', 'artifact:minisign-v1']
  const runtimeTargetsReady = targets.length > 0 && targets.every(id => { const server = servers.find(value => value.id === id); return server?.online && runtimeCapabilities.every(capability => server.capabilities?.includes(capability)) })
  const panelPositions = plan.steps.flatMap((step, index) => step.kind === 'panel_backup' ? [index] : [])
  const planIssue = panelPositions.length > 1 || (panelPositions.length === 1 && panelPositions[0] !== 0) ? '完整面板备份至多一次且必须为第一步。请明确移动到首步或移除多余步骤，系统不会自行调整顺序。' : actor && plan.steps.some(step => !canChoose(actor, step.kind)) ? '当前方案包含未授权的步骤。请调整方案；原有草稿仍保留。' : plan.steps.some(step => step.kind === 'panel_backup' && !step.backup_schedule_id) ? '请为面板完整备份明确选择已登记计划。' : plan.steps.some(step => step.kind === 'singbox_retry_deployment' && step.runtime_version !== '1.14.2') ? '此方案的部署版本已不支持。请明确重新选择固定失败部署步骤。' : plan.steps.some(step => step.kind === 'singbox_retry_deployment') && !runtimeTargetsReady ? '固定失败部署步骤的每个目标都须在线并声明运行时运维、精确配置核对与制品验签能力。' : ''
  const canWrite = allows(actor, 'operations:write')
  const ready = canWrite && targets.length > 0 && !planIssue
  const targetNote = (server: Server) => {
    const capabilities = server.capabilities ?? []
    if (plan.steps.some(step => step.kind === 'singbox_retry_deployment') && !runtimeCapabilities.every(capability => capabilities.includes(capability))) return '缺少运行时运维、精确核对或验签能力'
    if (plan.steps.some(step => step.kind === 'singbox_retry_deployment') && !server.online) return '离线，不能核对固定失败部署'
    if (plan.steps.some(step => step.kind !== 'panel_backup' && step.kind !== 'singbox_retry_deployment') && !capabilities.includes('fleet:operations:v1')) return '需升级并授权日常运维'
    return plan.steps.every(step => step.kind === 'panel_backup') ? '仅关联任务；备份在面板执行一次' : server.online ? '能力已声明，仍须预览核对授权和当前状态' : '离线，日常操作排队等待'
  }

  return <div className="operations-stack">
    <section className="operations-card">
      <h3>固定目标与操作方案</h3>
      <p>先执行一台，再按固定批次继续。步骤成功后才执行下一步；超时或断线后保留未知状态，需核对后处理。</p>
      <FormDraftToolbar draftKey="operations-plan" value={draft} dirty={JSON.stringify(draft) !== draftBaseline} onRestore={restoreDraft} onSaved={value => setDraftBaseline(JSON.stringify(value))} description="仅保存操作类型、受管服务名、版本、备份计划引用与固定目标，不包含凭据或命令。跨窗口保存会核对草稿版本；失败保留当前输入。" />
      {draftIssue && <p role="alert">{draftIssue}</p>}
      <label>方案名称<input value={plan.name} onChange={event => change({ ...plan, name: event.target.value })} maxLength={128} /></label>
      <label>套用模板<select value={templateId ?? ''} onChange={event => { const template = templates.find(value => value.id === event.target.value); if (template) { setPlan({ ...plan, name: template.name, steps: template.steps.map(step => ({ ...step, runtime_version: step.kind === 'singbox_retry_deployment' ? step.runtime_version ?? '1.14.2' : null, backup_schedule_id: step.kind === 'panel_backup' ? step.backup_schedule_id ?? null : null })) }); setTemplateId(template.id); setPreview(null) } }}><option value="">选择固定步骤模板</option>{templates.map(template => <option key={template.id} value={template.id}>{template.name}</option>)}</select></label>
      <fieldset><legend>提交时固定服务器范围（{targets.length} 台）</legend><div className="operations-targets">{servers.map(server => <label key={server.id}><input type="checkbox" disabled={!allowTargetSelection || !canWrite} checked={targets.includes(server.id)} onChange={() => toggle(server.id)} />{server.name}<small>{targetNote(server)}</small></label>)}</div></fieldset>
      {plan.steps.map((step, index) => <div className="operations-step" key={index}><strong>步骤 {index + 1}</strong><StepEditor step={step} index={index} backups={globalServers(actor) && allows(actor, 'recovery:read') ? backupSchedules : []} choices={(Object.keys(stepNames) as Step['kind'][]).filter(kind => canChoose(actor, kind) && (kind !== 'singbox_retry_deployment' || runtimeTargetsReady) && (kind !== 'panel_backup' || (index === 0 && !plan.steps.some((existing, position) => position !== index && existing.kind === 'panel_backup'))))} update={next => updateStep(index, next)} />{step.kind === 'panel_backup' && index > 0 && <button onClick={() => change({ ...plan, steps: [step, ...plan.steps.filter((_, position) => position !== index)] })}>明确移至第一步</button>}<button type="button" disabled={plan.steps.length === 1} onClick={() => change({ ...plan, steps: plan.steps.filter((_, position) => position !== index) })}>移除</button></div>)}
      {planIssue && <p role="alert">{planIssue}</p>}
      {!actor && <p>正在读取当前权限；读取成功后才提供执行器和备份设置。</p>}
      {actor && !canChoose(actor, 'singbox_retry_deployment') && <p>固定失败部署重试需要运维写入、代理业务读写授权及目标 Agent 实际能力。</p>}
      {actor && canChoose(actor, 'singbox_retry_deployment') && !runtimeTargetsReady && <p>先选择在线且支持运行时运维、实际配置核对与制品验签的目标，才可选择固定失败部署步骤。</p>}
      {actor && !canChoose(actor, 'panel_backup') && <p>完整面板恢复点需要全服务器范围的恢复读写授权；局部服务器授权不会显示全局备份选择器。</p>}
      <button disabled={!canWrite || plan.steps.length >= 16} onClick={() => change({ ...plan, steps: [...plan.steps, { kind: 'system_snapshot', service: null, timeout_secs: 300 }] })}>添加步骤</button>
      <div className="operations-fields"><label>后续批次大小<input type="number" min={1} max={32} value={plan.batch_size} onChange={event => change({ ...plan, batch_size: Number(event.target.value) })} /></label><label>最大并发<input type="number" min={1} max={16} value={plan.concurrency} onChange={event => change({ ...plan, concurrency: Number(event.target.value) })} /></label><label>总时长预算（秒）<input type="number" min={60} max={86400} value={plan.max_duration_secs} onChange={event => change({ ...plan, max_duration_secs: Number(event.target.value) })} /></label><label><input type="checkbox" checked={plan.pause_between_batches} onChange={event => change({ ...plan, pause_between_batches: event.target.checked })} />每批继续前确认</label></div>
      <div className="operations-actions"><button disabled={!ready} onClick={() => run(async () => setPreview(await api<Preview>('/api/operations/preview', 'POST', { plan, targets, template_id: templateId })))}>预览目标与影响</button><button disabled={!canWrite || Boolean(planIssue)} onClick={() => run(async () => { await api('/api/operations/templates', 'POST', { name: plan.name, steps: plan.steps }); setTemplates(await api<Template[]>('/api/operations/templates')); setDraftBaseline(JSON.stringify(draft)) })}>保存固定模板</button></div>
      {preview && <div className="operations-review"><h4>执行预览</h4><p>{preview.spec.target_snapshot.map(server => server.name).join('、')}；{preview.spec.plan.steps.length} 个步骤；预览有效至 {time(preview.expires_at)}。</p><ol>{preview.spec.plan.steps.map((step, index) => <li key={index}>{stepNames[step.kind]} {step.service ?? ''}</li>)}</ol><TypedPreview preview={preview} servers={servers} /><button disabled={!ready} onClick={() => run(async () => { await api(`/api/operations/jobs/${preview.id}/confirm`, 'POST', { digest: preview.digest }); await loadDetail(preview.id); setPreview(null); setJobs(await api<Job[]>('/api/operations/jobs')); setDraftBaseline(JSON.stringify(draft)) }, true)}>验证身份并确认执行</button></div>}
    </section>
    <section className="operations-card"><h3>任务与逐台结果</h3><div className="operations-table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>目标</th><th>最后变化</th><th>操作</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td>{job.name}</td><td>{states[job.status] ?? job.status}<small>{job.failure_reason}</small></td><td>{job.targets.length} 台</td><td>{time(job.updated_at)}</td><td><button onClick={() => run(() => loadDetail(job.id))}>详情</button></td></tr>)}</tbody></table></div>{!jobs.length && <p>暂无任务。</p>}</section>
    {detail && <section className="operations-card"><h3>{detail.job.name} · {states[detail.job.status] ?? detail.job.status}</h3><p>{detail.job.failure_reason}</p><div className="operations-actions"><button onClick={() => run(() => loadDetail(detail.job.id))}>刷新设备回执</button>{canWrite && detail.job.status === 'paused' && <button onClick={() => run(async () => { await api(`/api/operations/jobs/${detail.job.id}/resume`, 'POST'); await loadDetail(detail.job.id) }, true)}>验证身份并继续固定批次</button>}{canWrite && !['succeeded', 'failed', 'cancelled'].includes(detail.job.status) && <button onClick={() => run(async () => { await api(`/api/operations/jobs/${detail.job.id}/cancel`, 'POST'); await loadDetail(detail.job.id) })}>请求取消后续步骤</button>}</div><p>尚未交付设备的操作可取消。已交付的受限服务操作必须等待结果；请求取消不代表进程已停止。</p><div className="operations-table-wrap"><table><thead><tr><th>服务器</th><th>批次／步骤</th><th>状态</th><th>结果</th></tr></thead><tbody>{detail.steps.map(step => <tr key={`${step.server_id}-${step.position}`}><td>{servers.find(server => server.id === step.server_id)?.name ?? step.server_id}</td><td>{step.batch === 0 ? '首台' : `批次 ${step.batch}`}／{step.position + 1}</td><td>{states[step.state] ?? step.state}</td><td><details><summary>查看原始回执</summary><pre>{JSON.stringify(step.execution_result ?? step.result, null, 2)}</pre></details>{step.state === 'uncertain' && step.fleet_operation_id && canWrite && <button onClick={() => setReconciliation({ server: step.server_id, operation: step.fleet_operation_id! })}>核对日常操作进程停止</button>}{step.state === 'uncertain' && step.runtime_operation_id && <p>原部署结果未知，须使用下面的实际配置核对流程。</p>}</td></tr>)}</tbody></table></div><TypedResults detail={detail} actor={actor} run={run} refresh={() => loadDetail(detail.job.id)} />{reconciliation && detail.steps.some(step => step.server_id === reconciliation.server && step.fleet_operation_id === reconciliation.operation && step.state === 'uncertain') && <FleetReconciliation key={`${detail.job.id}:${reconciliation.operation}`} job={detail.job.id} server={reconciliation.server} original={reconciliation.operation} run={run} refresh={() => loadDetail(detail.job.id)} close={() => setReconciliation(null)} />}<details><summary>任务阶段、取消与核对记录</summary>{detail.history.map(entry => <p key={entry.id}>{time(entry.recorded_at)} · {actionNames[entry.action] ?? '任务记录'}<pre>{JSON.stringify(entry.details, null, 2)}</pre></p>)}</details></section>}
    <section className="operations-card"><h3>定时计划</h3><p>复用上面的固定目标与步骤。执行前再次检查提交者权限；已有任务尚未确认结果时跳过新窗口。</p><div className="operations-fields"><label>首次执行（本地时区）<input type="datetime-local" value={scheduleAt} onChange={event => setScheduleAt(event.target.value)} /></label><label>周期（秒）<input type="number" min={300} value={interval} onChange={event => setInterval(Number(event.target.value))} /></label><label>最大执行次数<input type="number" min={1} max={10000} value={maxRuns} onChange={event => setMaxRuns(Number(event.target.value))} /></label><label>错过窗口<select value={missed} onChange={event => setMissed(event.target.value)}><option value="skip">跳过</option><option value="run_once">补执行一次</option></select></label></div><button disabled={!ready || !scheduleAt} onClick={() => run(async () => { await api('/api/operations/schedules', 'POST', { name: plan.name, plan, targets, next_run_at: Math.floor(new Date(scheduleAt).getTime() / 1000), interval_secs: interval, timezone_offset_minutes: currentZoneOffset, missed_policy: missed, max_runs: maxRuns }); setSchedules(await api<Schedule[]>('/api/operations/schedules')); setDraftBaseline(JSON.stringify(draft)) }, true)}>验证身份并创建计划</button>{schedules.map(schedule => <p key={schedule.id}>{schedule.name} · {schedule.paused ? '已暂停' : `下次 ${time(schedule.next_run_at)}`} · {schedule.run_count}/{schedule.max_runs} 次 <button onClick={() => run(async () => { await api(`/api/operations/schedules/${schedule.id}/pause`, 'POST', { paused: !schedule.paused }); setSchedules(await api<Schedule[]>('/api/operations/schedules')) }, schedule.paused)}>{schedule.paused ? '恢复计划' : '人工暂停'}</button></p>)}</section>
    <section className="operations-card"><h3>维护窗口</h3><p>维护期间继续保留监测与事件，按选择抑制通知及停止接收新任务。</p><div className="operations-fields"><label>开始<input type="datetime-local" value={maintenanceStart} onChange={event => setMaintenanceStart(event.target.value)} /></label><label>结束<input type="datetime-local" value={maintenanceEnd} onChange={event => setMaintenanceEnd(event.target.value)} /></label><label><input type="checkbox" checked={suppress} onChange={event => setSuppress(event.target.checked)} />抑制计划内通知</label><label><input type="checkbox" checked={blockTasks} onChange={event => setBlockTasks(event.target.checked)} />停止接收新任务</label></div><button disabled={!canWrite || !targets.length || !maintenanceStart || !maintenanceEnd} onClick={() => run(async () => { await api('/api/operations/maintenance', 'POST', { name: plan.name, targets, starts_at: Math.floor(new Date(maintenanceStart).getTime() / 1000), ends_at: Math.floor(new Date(maintenanceEnd).getTime() / 1000), suppress_notifications: suppress, block_new_tasks: blockTasks }); setMaintenance(await api<Maintenance[]>('/api/operations/maintenance')) })}>创建所选服务器维护窗口</button>{maintenance.map(window => <p key={window.id}>{window.name} · {window.targets.length} 台 · {time(window.starts_at)} 至 {time(window.ends_at)}</p>)}</section>
    {plan.steps.every(step => step.kind !== 'panel_backup' && step.kind !== 'singbox_retry_deployment') ? <RemediationRules plan={plan} targets={targets} run={run} version={version} /> : <section className="operations-card"><h3>有界自动处置</h3><p>自动处置当前仅支持系统快照及已授权服务操作。完整备份和固定部署重试须使用上面的明确方案与任务计划。</p></section>}
    <CancellationReminders run={run} version={version} />
  </div>
}
