export type Step = { kind: 'system_snapshot' | 'service_status' | 'service_start' | 'service_stop' | 'service_restart' | 'singbox_retry_deployment' | 'panel_backup'; service: string | null; timeout_secs: number; runtime_version?: string | null; backup_schedule_id?: string | null }
export type Plan = { name: string; steps: Step[]; batch_size: number; concurrency: number; pause_between_batches: boolean; max_duration_secs: number }
export type Job = { id: string; name: string; status: string; targets: number[]; requested_by: number; created_at: number; updated_at: number; expires_at?: number; failure_reason: string | null; spec?: { plan: Plan } }
export type RuntimeDeploymentCandidate = { kind: string; module: string; runtime_version: string; binding: { deployment_id: string; revision: number; bundle_sha256: string; binding_digest: string }; artifact: { sha256: string; arch: string; bytes: string; version: string; signature_verified: boolean; payload_verified: boolean; source_repo: string; release_tag: string }; target_status_updated_at: number }
export type TypedStepPreview = { position: number; kind: Step['kind']; targets?: Record<string, RuntimeDeploymentCandidate>; version?: string; scope?: string; backup?: { id: string; name: string; recipient: string; paused: boolean; retention_count: number; retention_days: number }; backup_digest?: string; once_per_job?: boolean }
export type Preview = { id: string; digest: string; expires_at: number; spec: { plan: Plan; target_snapshot: { id: number; name: string }[]; typed_steps?: TypedStepPreview[] } }
export type JobDetail = { job: Job; steps: { server_id: number; position: number; batch: number; state: string; execution_state: string | null; execution_result: unknown; result: unknown; running_cancel_supported: boolean; fleet_operation_id?: string | null; runtime_operation_id?: string | null }[]; panel_steps?: { position: number; state: string; execution_id: string; backup_id: string | null; claimed_at: number | null; finished_at: number | null; result: unknown }[]; history: { id: number; action: string; recorded_at: number; details: unknown }[] }
export type BackupScheduleOption = { id: string; name: string; paused: boolean; recipient: string; retention_count: number; retention_days: number }
export type Template = { id: string; name: string; steps: Step[] }
export type Schedule = { id: string; name: string; targets: number[]; paused: boolean; next_run_at: number; run_count: number; max_runs: number; interval_secs: number; timezone_offset_minutes: number; missed_policy: string }
export type Maintenance = { id: string; name: string; targets: number[]; starts_at: number; ends_at: number; suppress_notifications: boolean; block_new_tasks: boolean }
export type Incident = { id: string; title: string; severity: string; status: string; server_id: number | null; opened_at: number; observed_at: number; acknowledged_by: number | null; assignee: number | null; escalated_at: number | null; resolved_at: number | null; evidence: unknown; recovery_evidence: unknown; maintenance_suppressed: boolean }
export type BackupRecord = { id: string; name: string; location: string; encrypted: boolean; verification: string; created_at: number; manifest_sha256: string; retired_at: number | null; drills: { id: string; passed: boolean; recorded_at: number; report: unknown }[] }
export type CloudResource = { id: string; name: string; cloud_id: string; account_name: string; kind: string; region: string; snapshot: { public_ip: string; status: string; bandwidth_mbps: number; charge_type: string } | null; checked_at: number | null; error_code: string | null; bill_error: string | null; bill_stale: boolean; actual_costs_by_currency: Record<string, string>; instance_bill: { month: string; queried_at: number } | null; manual_hold: boolean; link: { server_id: number | null; purchase_reference: string; purchase_amount: string | null; currency: string | null; monthly_budget: string | null; expires_at: number | null; notes: string } | null }
export type ActionRunner = (action: () => Promise<void>, proof?: boolean) => void
export const time = (value: number | null | undefined) => value ? new Date(value * 1000).toLocaleString('zh-CN') : '暂无观测'
export const states: Record<string, string> = { preview: '待确认', queued: '排队', pending: '等待依赖', running: '执行中', paused: '待批次确认', cancel_requested: '取消请求已记录', cancelled: '已取消', succeeded: '已完成', failed: '失败', uncertain: '结果未知', unknown: '结果未知', dispatched: '已交付设备', skipped: '未执行', expired: '领取过期', open: '待处理', acknowledged: '已确认', resolved: '已有依据恢复', declared: '清单已登记', integrity_verified: '已有完整性证据', restored: '已有恢复证据' }
